### ISSUE TITLE
run on Mac Mojave: Unable to load Info.plist exceptions (eGPUOverrides)

### ISSUE THREAD

**Issue by hxu927** [praat/praat#1029]
hi,
when I run Praat through source on Mac Mojave, build successfully, but do not display waveform.
I check the log and find "Unable to load Info.plist exceptions (eGPUOverrides)",
do anyone know how to fix it?

**Comment by PaulBoersma** [comment]
Just building from source will not work; you will have to work with the xcodeproj file provided, which says that the Base SDK has to be macOS 10.13. We will fix this later; meanwhile, you should copy the 10.13 SDK into your Xcode app.
