### ISSUE TITLE
Console output printed to new line in Windows

### ISSUE THREAD

**Issue by abeith** [praat/praat#1033]
When using Praat from the command line in Windows, outputs are printed after a new line. 

![praatoutput](https://user-images.githubusercontent.com/44166927/63358433-ee13d800-c362-11e9-8cfe-a49b81778ac8.png)

Hitting return brings up the next prompt. However, I often execute Praat scripts from the system function in R. Only the first character of an error message gets sent to stdout.

![routput](https://user-images.githubusercontent.com/44166927/63359171-2ff14e00-c364-11e9-85b5-5616f48546ee.png)

I don't have this issue with either Linux (Ubuntu) or Mac.

**Comment by PaulBoersma** [comment]
Praat sends its answer in UTF-16, and R does not seem to understand that. Use UTF-8 instead, i.e. say "praat --utf8 --version" or "praat -8 --version".
