### ISSUE TITLE
Jack Dependency issue while compiling for linux

### ISSUE THREAD

**Issue by SarveshBajaj** [praat/praat#1062]
I was trying to set up the required libraries for praat on my linux.
On running the "make" command, this error is shown:

pa_jack.c:63:10: fatal error: jack/types.h: No such file or directory,

I checked and found that a  certain "jack" dependency must be added.
This is the link where this problem has been stated as well:

https://aur.archlinux.org/packages/praat/#comment-676581

I need the information of which dependency to be added and the process to do it.

**Comment by ssorcerer** [comment]
Same problem here @SarveshBajaj . Installing libjack-dev on ubuntu solved the issue. It seems this version is good.


>$ apt show libjack-dev 
Package: libjack-dev
Version: 1:0.125.0-3
Priority: optional
Section: universe/libdevel
Source: jack-audio-connection-kit

**Comment by vikramSeth679** [comment]
Thanks, I'll close this issue now.

**Comment by SarveshBajaj** [comment]
Thanks, I'll close this issue now
