### ISSUE TITLE
Crash every time when trying select using left click then drag

### ISSUE THREAD

**Issue by Alice-Shi** [praat/praat#1070]
error massages are as follow:

Praat will crash. Notify the author(paul.boersma@uva.nl) with the following information:

Assertion failed in file "/Users/pboersma/Dropbox/Praats/src/sys/
Graphics_colour.cpp" at line 234:

Every message was exacatly the same whatever audio file(mp3 or wav)  I was using.
OS: macOS 10.14.6 praat version: 6.1.04

**Comment by PaulBoersma** [comment]
This has been repaired in 6.1.05.
