### ISSUE TITLE
Failing tests due to `long double` on Rasbperry Pi and MSVC-compiled Windows

### ISSUE THREAD

**Issue by YannickJadoul** [praat/praat#1170]
On Raspberry Pi (and Windows, when compiling with Microsoft's MSVC), Praat's tests are failing because `long double` does not offer more precision than a normal `double` (as allowed by the C++ standard).

The first failure of the test suite is in [`test/num/mean.praat`, line 74](https://github.com/praat/praat/blob/d51e454831733384307bde13b837c87921b82a18/test/num/mean.praat#L74), where `(1e18 + 3 + -1e18) / 3` does not equal 1 with normal double precision floating-point numbers.

Is this problematic for these platforms; does Praat require extended precision for full correctness? If so, is MSVC not supported and should I be compiling with another compiler on Windows? Or is the test too strong?

**Comment by PaulBoersma** [comment]
Praat should be fine with 64-bit long doubles, profiting only from them on platforms where they have more bits than that. I have changed this to warning-only for 6.1.11.

**Comment by YannickJadoul** [comment]
OK, thanks for the confirmation!
