### ISSUE TITLE
`TextGrid_TIMITLabelFileRecognizer` fails on MSVC Windows

### ISSUE THREAD

**Issue by YannickJadoul** [praat/praat#1172]
There are two `scanf` calls with `%ld` format specifier receiving `integer`s instead of `long_not_integer`, resulting in potential problems when compiling with VS 2019's MSVC:

https://github.com/praat/praat/blob/c16ffb6736076e9c7a8bd0aa2b83ec704b22f37e/dwtools/TextGrid_extensions.cpp#L161-L164

https://github.com/praat/praat/blob/c16ffb6736076e9c7a8bd0aa2b83ec704b22f37e/dwtools/TextGrid_extensions.cpp#L228-L231

**Comment by PaulBoersma** [comment]
thanks. Solved in 6.1.10
