### ISSUE TITLE
Fix for building 6.1.10

### ISSUE THREAD

**Issue by brechtsanders** [praat/praat#1239]
When building the recently released version 6.1.10 in my MinGW/MSYS2 environment I got this error
```
make[1]: Entering directory '/R/winlibs64-9.2.0/praat-6.1.10/fon'
g++ -std=c++14 -Wshadow -DWINVER=0x0500 -D_WIN32_WINNT=0x0500 -D_WIN32_IE=0x0500 -DUNICODE -Dmain=wingwmain -O1 -D_FILE_OFFSET_BITS=64 -D_USE_MATH_DEFINES -I ../kar -I ../melder -I ../sys -I ../dwsys -I ../stat -I ../dwtools -I ../LPC -I ../fon -I ../external/portaudio -I ../external/flac -I ../external/mp3 -I ../external/espeak  -c -o Photo.o Photo.cpp
Photo.cpp: In function 'void _Photo_cellArrayOrImage(Photo, Graphics, double, double, double, double, bool)':
Photo.cpp:450:13: error: missing template arguments before 'z'
  450 |  automatrix z = newmatrixraw <MelderColour> (iymax - (iymin - 1), ixmax
- (ixmin - 1));
      |             ^
Photo.cpp:453:25: error: 'z' was not declared in this scope
  453 |    MelderColour& cell = z [iy - (iymin - 1)] [ix - (ixmin - 1)];
      |                         ^
Photo.cpp:461:29: error: 'z' was not declared in this scope
  461 |   Graphics_image_colour (g, z.all(),
      |                             ^
Photo.cpp:465:33: error: 'z' was not declared in this scope
  465 |   Graphics_cellArray_colour (g, z.all(),
      |                                 ^
make[1]: *** [<builtin>: Photo.o] Error 1
make[1]: Leaving directory '/R/winlibs64-9.2.0/praat-6.1.10/fon'
make: *** [Makefile:28: all] Error 2
```

which can be fixed with this patch:
```
patch -ulbf fon/Photo.cpp << EOF
@@ -449,3 +449,3 @@
        Graphics_setWindow (g, xmin, xmax, ymin, ymax);
-       automatrix z = newmatrixraw <MelderColour> (iymax - (iymin - 1), ixmax - (ixmin - 1));
+       automatrix<MelderColour> z = newmatrixraw <MelderColour> (iymax - (iymin - 1), ixmax - (ixmin - 1));
        for (integer iy = iymin; iy <= iymax; iy ++) {
EOF
```

I'm not sure that is the correct fix for the problem, but I thought I'd share this with you.

**Comment by PaulBoersma** [comment]
You are using a very old makefile. Please use a current one instead. The main difference is that you are using C++14, whereas Praat requires C++17.

**Comment by brechtsanders** [comment]
Strange, I downloaded the tarball from https://github.com/praat/praat/archive/v6.1.10.tar.gz extracted it and ran make.
Note that my environment has the latest GCC 9.3.0 which has full support for `-std=c++17`.
Which make file was I supposed to use?

Met vriendelijke groeten,
Brecht

**Comment by PaulBoersma** [comment]
dear Brecht,

you should follow the guideline for building from sources on Linux (see section 3.3 in README.md), which tells you you should typically do

cp makefiles/makefile.defs.linux.pulse ./makefile.defs
make

If you skip the first line, and you did compile Praat before, you will be using the older makefile.defs from your previous compilation.

best wishes,
Paul

> On 24 Mar 2020, at 19:17, Brecht Sanders <notifications@github.com> wrote:
> 
> 
> Strange, I downloaded the tarball from https://github.com/praat/praat/archive/v6.1.10.tar.gz extracted it and ran make.
> Note that my environment has the latest GCC 9.3.0 which has full support for -std=c++17.
> Which make file was I supposed to use?
> 
> Met vriendelijke groeten,
> Brecht
> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

_____

Paul Boersma
Professor of Phonetic Sciences, University of Amsterdam

Visiting address: Spuistraat 134, room 632, Amsterdam
Mail: P.O. Box 1642, 1000BP Amsterdam, The Netherlands
Website: http://www.fon.hum.uva.nl/paul/

**Comment by PaulBoersma** [comment]
And to help you realize this, the tarball does not include makefile.defs in the root directory, so that just typing "make" after downloading and unpacking should give a "File makefile.defs not found" error message. Also, you should always build from a cleanly unpacked folder, so that older cpp files are not included in your build.

> On 24 Mar 2020, at 19:17, Brecht Sanders <notifications@github.com> wrote:
> 
> 
> Strange, I downloaded the tarball from https://github.com/praat/praat/archive/v6.1.10.tar.gz extracted it and ran make.
> Note that my environment has the latest GCC 9.3.0 which has full support for -std=c++17.
> Which make file was I supposed to use?
> 
> Met vriendelijke groeten,
> Brecht
> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

_____

Paul Boersma
Professor of Phonetic Sciences, University of Amsterdam

Visiting address: Spuistraat 134, room 632, Amsterdam
Mail: P.O. Box 1642, 1000BP Amsterdam, The Netherlands
Website: http://www.fon.hum.uva.nl/paul/

**Comment by brechtsanders** [comment]
Ok, thanks.
The files makefiles/makefile.defs.mingw32/64 worked for me provided I emptied PREFIX.
