### ISSUE TITLE
Raspberry PI3 stretch

### ISSUE THREAD

**Issue by profmarzi** [praat/praat#1242]
Hi
Compilation without error but wornings. Program opens from desktop menu. Loading a wav file this message is given
Praat will crash. Notify the author (paul.boersma@uva.nl) with the following information:
Assertion failed in file "praat.cpp" at line 1614:
   sizeof (real80) >= 12

**Comment by PaulBoersma** [comment]
That bug was corrected in February 2018. Please use a more recent version of Praat.
