### ISSUE TITLE
Strange crash in Inspect DataEditor, Linux version 6.1.14

### ISSUE THREAD

**Issue by no-buddy** [praat/praat#1259]
If I run this script:

`Create Sound from formula: "1", 1, 0, 1, 10, "sin(2*pi*x)"`
`Inspect`

praat opens a DataEditor.
Then I click on the "Change" button and praat crashes with these errors:

(praat:22665): GLib-GObject-WARNING **: 19:32:48.898: invalid cast from '(null)' to 'GObject'

(praat:22665): GLib-GObject-CRITICAL **: 19:32:48.898: g_object_get: assertion 'G_IS_OBJECT (object)' failed

(praat:22665): GLib-GObject-WARNING **: 19:32:48.898: invalid cast from '(null)' to 'GObject'

(praat:22665): GLib-GObject-CRITICAL **: 19:32:48.898: g_object_get: assertion 'G_IS_OBJECT (object)' failed

(praat:22665): GLib-GObject-WARNING **: 19:32:48.898: invalid cast from '(null)' to 'GObject'

(praat:22665): GLib-GObject-CRITICAL **: 19:32:48.898: g_object_get: assertion 'G_IS_OBJECT (object)' failed

(praat:22665): GLib-GObject-WARNING **: 19:32:48.898: invalid cast from '(null)' to 'GObject'

(praat:22665): GLib-GObject-CRITICAL **: 19:32:48.898: g_object_get: assertion 'G_IS_OBJECT (object)' failed

(praat:22665): GLib-GObject-WARNING **: 19:32:48.898: invalid cast from '(null)' to 'GObject'

(praat:22665): GLib-GObject-CRITICAL **: 19:32:48.898: g_object_get: assertion 'G_IS_OBJECT (object)' failed

(praat:22665): GLib-GObject-WARNING **: 19:32:48.898: invalid cast from '(null)' to 'GObject'

(praat:22665): GLib-GObject-CRITICAL **: 19:32:48.898: g_object_get: assertion 'G_IS_OBJECT (object)' failed

(praat:22665): GLib-GObject-WARNING **: 19:32:48.898: invalid cast from '(null)' to 'GObject'

(praat:22665): GLib-GObject-CRITICAL **: 19:32:48.898: g_object_get: assertion 'G_IS_OBJECT (object)' failed

(praat:22665): GLib-GObject-WARNING **: 19:32:48.898: invalid cast from '(null)' to 'GObject'

(praat:22665): GLib-GObject-CRITICAL **: 19:32:48.898: g_object_get: assertion 'G_IS_OBJECT (object)' failed

(praat:22665): GLib-GObject-WARNING **: 19:32:48.898: invalid cast from '(null)' to 'GObject'

(praat:22665): GLib-GObject-CRITICAL **: 19:32:48.898: g_object_get: assertion 'G_IS_OBJECT (object)' failed

(praat:22665): GLib-GObject-WARNING **: 19:32:48.898: invalid cast from '(null)' to 'GObject'

(praat:22665): GLib-GObject-CRITICAL **: 19:32:48.898: g_object_get: assertion 'G_IS_OBJECT (object)' failed

(praat:22665): GLib-GObject-WARNING **: 19:32:48.898: invalid cast from '(null)' to 'GObject'

(praat:22665): GLib-GObject-CRITICAL **: 19:32:48.898: g_object_get: assertion 'G_IS_OBJECT (object)' failed

**Comment by PaulBoersma** [comment]
This bug no longer appears in newer versions.
