### ISSUE TITLE
Please no static libraries for linux

### ISSUE THREAD

**Issue by imsedgar** [praat/praat#1289]
Dear Paul,

I have tried to build a new Fedora rpm package from praat version 6.1.12 and it failed with error. I checked the reason and found linking problems.
Why did you add linker options "-static-libgcc -static-libstdc++" to makefiles/makefile.defs.linux.* in patch 1aab2280e9c9b0b03745897cf142344860c2781a ?

These two libraries are (most likely) installed as shared libraries in almost every Linux installation where users work with praat. When shared system libraries are updated by the operating system, e.g. as security updates, all applications using these shared libraries will also receive these updates. Statically linked libraries, on the other hand, remain at the old (possibly unsafe) state.

Therefore, for security reasons, it should be avoided, whenever possible, to bind libraries statically.

What is the reason for this change?

PS: For our packages build on Fedora, I have patched the source to remove these linker options. Also, as you may remember, I also patch the source to remove references to your external directory with flac, glpk, gls, gs and portaudio from the makefiles and replace them by the (shared) system versions. It works successful for since many years. We don't want your old versions in our executables.

I also wonder why CLAPACK is now included here in the source code instead of using existing system libraries.

**Comment by PaulBoersma** [comment]
The reason for the change is that we had to use *newer* versions of the libraries than some users have (both gcc and stdc++). This was especially true for 32-bit Ubuntu 18.04. Somebody who builds a package for a fixed Linux distribution will indeed not include these libraries statically. Using unpatched versions of flac, glpk, gsl and portaudio will cause Praat to misbehave. We also had to patch the Clapack sources. Details are in the READ_ME.TXT files. The Praat edition that you are distributing is probably unsafe.

**Comment by imsedgar** [comment]
Thanks for the answer and for the note to READ_ME.TXT files.

Your patches are against old versions of these external software packages, and they are the same old versions since a long time. At least you should update them to current upstream and check if your patches are still necessary. But the best solution would be to integrate your patches in the upstream sources, so the next release will include them for all users. If your patches are not suitable for all users, then it would be better to create a function that is specific to praat and it can call the original code for all other that fits for praat.

If _some_ users use older versions than praat needs, then it would be best to declare it somewhere in the readme, release notes, build notes, and check is with scripts and at runtime. Then it would work on all systems. You can optionally offer a simple way to directly integrate the required software versions as external software, but it should be only done for users who want it. Or at least, you should create an additional makefiles/makefile.defs.linux.* file for those special users who as old software.

It would be ok if you _temporary_ add patches for software while patches are not included upstream. But if they fix it in a new version, then you should refer to require the fixed upstream version (or a newer one), which usually find there way to the common Linux distributions too. Then (after some time to distribute) you can (should) remove your manual patched external version (or at least include it only if the user specifies it during building from source).

My colleagues have been using praat on Fedora for many years with the build options I use without any problems resulting from this. (At least one of them has regular contact with you).

**Comment by PaulBoersma** [comment]
We do renew our versions now and then, such as Clapack recently, as you noted. It was the most recent version, and it had several major bugs in the source, as described in its READ_ME.TXT. It depended on the compiler or loader whether these bugs led to problems or not. Better to have our patched version, I would say. There are such examples for other libraries as well. Perhaps I should create scripts that elicit these bugs (or sometimes they are just failures to collaborate).

You know, what you are stating would be correct in an ideal world. Instead, however, we have to work with real software by others. All those pieces of software are big bug bins. As Praat developers, we only have to solve the bugs that are relevant for the uses of this external software in Praat. (and, but let's not talk about that yet, Praat should work not only on Linux but also on Mac and Windows, identically).

> If some users use older versions than praat needs, then it would be best to declare it somewhere in the readme, release notes, build notes, and check is with scripts and at runtime. Then it would work on all systems.

I don't understand. What should we then distribute? A Praat edition that announces that it needs at least GCC 8? It is virtually impossible (for a user who doesn't want to break the safety of /etc and the like) to install GCC 8 for 32-bit Ubuntu 18.04, which is the most recent of these recurrent problems.

> Or at least, you should create an additional makefiles/makefile.defs.linux.* file for those special users who as old software.

Of course we can provide multiple makefile.defs files. They all state, however, that the library list can be adapted, and one of the easiest adaptations is the removal of the -static phrases. I could add a commented-out version of that line for people who want to link dynamically. However, that would not solve the problem with statically linked libraries in the binaries that we also provide.

> It would be ok if you temporary add patches for software while patches are not included upstream.

How would that work? Patches in source code, in the context of an installed dso? Anyway, some patches are just Praat-specific. For instance, one of the external libraries calls setlocale!!! It's very hard to solve that obvious bug in an app-independent way.

> My colleagues have been using praat on Fedora for many years with the build options I use without any problems resulting from this. (At least one of them has regular contact with you).

Can you send me those build options? I might just provide it as an alternative, if they work. In actuality, I see a challenge here, namely to expose the bugs that I predicted in my previous message.

**Comment by PaulBoersma** [comment]
The default is again dynamic linking. There is a separate makefile for statically linked C and C++, which cannot make use of networking.
