### ISSUE TITLE
Ptich test +10x slower

### ISSUE THREAD

**Issue by YannickJadoul** [praat/praat#1332]
Commit https://github.com/praat/praat/commit/630f7d50d59ad9335f3c1cdc7d76f3a03e792cec#diff-de0af0af14f9be1b3ab09f2d23fc4d98 changes the time step used in of `test/fon/pitch.praat` and results in a test that takes more than ten times as long:

```
real	0m41,099s
user	0m40,783s
sys	0m0,116s
```
vs. 
```
real	9m40,564s
user	26m37,221s
sys	0m3,336s
```

I can't immediately find a clarification in the commit commit message or comments, so: to thoroughly test Praat, do I need to run tests with a step size this small, or can I save time running tests commenting out the new step size and using the old one?

**Comment by PaulBoersma** [comment]
This was not a mistake, but the next version will have the faster test again.

**Comment by YannickJadoul** [comment]
Great, thank you!
