### ISSUE TITLE
entering unicode broken on linux?

### ISSUE THREAD

**Issue by jonorthwash** [praat/praat#1343]
When editing a TextGrid, Praat's input dialogue (at the top of the window) does not allow me to enter non-ASCII symbols directly (using the keyboard).  I have tried extended Latin, combining diacritics, IPA, Cyrillic, Arabic, and Hebrew to no avail.  Copy-paste of these characters into the textbox *does* seem to work okay, as does the IPA character selector.

Occasionally (for some symbols?) it throws a warning like
```
** (praat:2955812): WARNING **: 16:55:37.662: Error converting text from IM to UTF-8: Invalid byte sequence in conversion input
```

I'm experiencing this issue on two different machines, both running Praat 6.1.16 directly from Debian.

**Comment by PaulBoersma** [comment]
How exactly did you try to enter these characters? Any input method or keyboard helper should work, but which one did you try?

**Comment by jonorthwash** [comment]
With xkb directly, no special input method overlays.

**Comment by PaulBoersma** [comment]
OK, can you tell me the exact steps by which you e.g. would expect to become able to start to enter Cyrillic characters?

**Comment by PaulBoersma** [comment]
I did it this way on Ubuntu 18.04: Settings -> Region & Language -> Keyboard -> Add -> Russian, then restart (?), and then switch keyboards via a little menu bar item that says "en" or "ru". I can then type Russian into the top text field of the TextGrid window without problem. пожалуйста.

**Comment by PaulBoersma** [comment]
Closed for lack of response.
