### ISSUE TITLE
Migrate to GTK3

### ISSUE THREAD

**Issue by rlaboiss** [praat/praat#1371]
I would like to draw your attention to the fact that GTK2 is deprecated (development stopped in 2011) and Debian is pushing the upstream authors to migrate to GTK3. Please, see [Bug#967708](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=967708), filed against the Debian praat package for details.

I guess that the migration GTK2 → GTK3 might be not straightforward.  Here is the [compilation log](https://github.com/praat/praat/files/5086532/make-praat-gtk3.log) against libgtk-3-dev.

**Comment by PaulBoersma** [comment]
We already prepared this a bit in our code, i.e. in line 67 of melder.h:
#define ALLOW_GDK_DRAWING  (gtk && 1)   /* change to (gtk && 0) if you want to try out GTK 3 */

**Comment by rlaboiss** [comment]
I tried this but it does not work.  I am applied this patch: [praat-gtk3.txt](https://github.com/praat/praat/files/5303153/praat-gtk3.txt) and using the Makefile `makefiles/makefile.defs.linux.pulse`.

This results in errors, cf the build log: [praat-gtk3-build.txt](https://github.com/praat/praat/files/5303157/praat-gtk3-build.txt)

Any recommendations for making this work ?

**Comment by PaulBoersma** [comment]
Thanks for the error listing. Yes, we have not finished this yet, but we are working on it. The current version of the source produces fewer errors than the one you were reporting on. Many of the uses of members of GDK or GTK structures have meanwhile been replaced with accessor functions, for instance. It has cost us four months to transfer to BigSur graphics on the Mac, and it will cost us less to transfer to GTK 3 on Linux. After that? Direct2D on Windows, I presume.

**Comment by rlaboiss** [comment]
Thanks for the reply, Paul. Indeed, with the source files form the master branch, only the following files have failed compilation:

- sendpraat.c
- GuiMenu.cpp
- GuiMenuItem.cpp
- GuiButton.cpp
- GuiOptionMenu.cpp
 
I will take a look at this, as time permits.

**Comment by rlaboiss** [comment]
> Thanks for the reply, Paul. Indeed, with the source files form the master branch, only the following files have failed compilation:
> 
> * sendpraat.c
> * GuiMenu.cpp
> * GuiMenuItem.cpp
> * GuiButton.cpp
> * GuiOptionMenu.cpp
> 
> I will take a look at this, as time permits.

Done in PR #1425

**Comment by PaulBoersma** [comment]
Version 6.1.31 has now been built with GTK-3, without any major or intermediate bugs that I know of.
