### ISSUE TITLE
Praat 6.1.24 - matrix - number of columns attribute sets to zero when assigning to another variable

### ISSUE THREAD

**Issue by rolandomunoz** [praat/praat#1429]
OS: Windows 10
Praat: 6.1.24 (64 bits)

In the following example, the number of columns of `a##` is not equal to `b##`. Is this a bug?

```
a## = zero##(0, 2)
b## = a##

writeInfoLine: numberOfColumns(a##), tab$, numberOfColumns(b##)

>> 2  0

```

Thank you for the new Praat version!

**Comment by PaulBoersma** [comment]
Repaired for Praat 6.1.52. Thanks for the clear report.
