### ISSUE TITLE
Please, add a desktop file to the distribution tarball

### ISSUE THREAD

**Issue by rlaboiss** [praat/praat#1438]
The Debian package for Praat has been shipping a [praat.desktop](https://github.com/praat/praat/files/5325463/praat.desktop.txt) which is installed in `/usr/share/applications/`. This is useful for desktop users, because the application can be easily found and an icon for it can be added to the user's desktop.

Please consider adding it to the distribution tarball.

**Comment by PaulBoersma** [comment]
Thanks! Now included in the folder `main`, together with the icon.
