### ISSUE TITLE
Mobile Version

### ISSUE THREAD

**Issue by VVKorol** [praat/praat#1471]
Do you have a plan for a portable app on a mobile platform?
It may be useful for working with informants which haven't a Windows laptop (for example in Africa, many people have mobile with Andriod, but usually they don't have a laptop).

**Comment by PaulBoersma** [comment]
Yes, we think about this a lot, but menu-controlled apps like Praat, which also require a user-visible file system, are not very compatible with smartphones and tablets, which tend to have a separate, and invisible, file system per app.
