### ISSUE TITLE
Tag a new version of Praat

### ISSUE THREAD

**Issue by mzhu65536-um** [praat/praat#1503]
OS: ArchLinux
Praat: 6.1.31 (as well as a3c884c) 

It was "unlucky" that I compiled both 6.1.31 yesterday and found that `Tab` as menu accelerator was not working in 6.1.31. Today, I compiled a3c884c, and surprisingly it works now. Would it be possible to tag and release the next version so that people will not get confused when using this buggy first GTK3 version of Praat? Thanks!

**Comment by PaulBoersma** [comment]
The repair of the tab callbacks took place with the commit called "Linux: reinstall tab callbacks", which was entered after the release of version 6.1.31. We typically release one new version per week, for all seven platforms. It is not feasible to create a new release with every single commit, i.e. multiple times per day. If there is a major bug, then of course we create a new release sooner; this bug, however, was minor.
