### ISSUE TITLE
No sound

### ISSUE THREAD

**Issue by tatulhum** [praat/praat#1508]
If my MacBook Air (iOS 10.13.6) goes to sleep and/or I unplug my headphones, Praat (v. 6.1.16) stops playing audio (nothing happens in a Sound window when the grey bar along the bottom of the sound is pressed or in the Objects window when selecting a Sound and pressing Play). Is there some way to get the audio back without restarting the program (and needing to reopen everything)?

**Comment by PaulBoersma** [comment]
Newer versions of Praat do not have this problem.
