### ISSUE TITLE
Cannot open file; File not finished

### ISSUE THREAD

**Issue by schelv** [praat/praat#1536]
Hi I can't open a .wav file recorded by a friend on his mac using praat.

this is the error message:
![praat error](https://user-images.githubusercontent.com/13403863/102268595-d11df380-3f1b-11eb-9fc3-b2f30d1e180e.PNG)

Other programs have no trouble opening the file.

**Comment by schelv** [comment]
Ok ive found out that the filenames contains these kinds of characters as a modifier to the letters:
http://www.fileformat.info/info/unicode/char/0300/index.htm
http://www.fileformat.info/info/unicode/char/0301/index.htm
http://www.fileformat.info/info/unicode/char/0304/index.htm
http://www.fileformat.info/info/unicode/char/030C/index.htm

If i remove these the file can be saved.

**Comment by PaulBoersma** [comment]
This was probably repaired in version 6.2.07.
