### ISSUE TITLE
Compiler complains about trigraphs

### ISSUE THREAD

**Issue by newbluemoon** [praat/praat#1542]
Hi,

I’m maintaining praat for [Void Linux](https://voidlinux.org).

When compiling there are a lot of warnings like
```
manual_exampleSound.cpp:1434:27: warning: trigraph ??> ignored, use -trigraphs to enable [-Wtrigraphs]
 1434 | "8<?648?833?:68?;=>?;>4?<1??>>6?>",
```

But it’s only in `fon/manual_exampleSound.cpp`. Because of using `-std=g++17` (from which trigraphs were removed) the warnings appear. Are these supposed to be trigraphs at all?

Can the warnings be safely ignored or should the option `-trigraphs` be used?

Thank you!

**Comment by adriaandegroot** [comment]
Those are not trigraphs, those are somewhat-strangely-encoded (base16) binary files. So you can ignore the warnings (puts me in mind to re-encode that and file a PR though).

**Comment by newbluemoon** [comment]
Thank you for the explanation and the fix. :)
