### ISSUE TITLE
Two-finger scrolling not working

### ISSUE THREAD

**Issue by takaakikagawa** [praat/praat#1588]
I remember Praat for Mac allowed for two-finger scrolling on the trackpad, but it doesn't seem to be working on my macOS 10.15.7 with Praat 6.1.38. Is there a way to enable it?

**Comment by takaakikagawa** [comment]
Apparently the scrolling does work on Praat 6.1.41, but extremely slowly.

**Comment by takaakikagawa** [comment]
Update: Suddenly one of the sound files scrolled smoothly by swiping, but no luck with other sound files. The View & Edit window of the file that worked had not been closed for hours.
(Praat v.6.1.42 and macOS 11.2.3)

**Comment by Clara-liu** [comment]
Any updates on this? I updated to the newest version of Praat (6.1.47) and the problem is still there.

**Comment by takaakikagawa** [comment]
> Any updates on this? I updated to the newest version of Praat (6.1.47) and the problem is still there.
> 
> Edit:
> After opening a sound window, click up or down arrow key (short cuts to move cursor) a few times and the scrolling will work again...

I still have this issue with Praat 6.1.50 on Big Sur 11.4. I tried pressing the arrow keys and that seems to enable two-finger scrolling somehow.

**Comment by PaulBoersma** [comment]
Two-finger scrolling on the trackpad should just work. It works only if the mouse pointer is over the window that you want to scroll, and you cannot scroll beyond the left or right edge of the sound.

Slowness can be due to showing formants. Do you have problems also after zooming in to, say, one second?

**Comment by PaulBoersma** [comment]
So many different things could be going on. Closing for lack of response.

**Comment by takaakikagawa** [comment]
I'm sorry to have missed your reply somehow. It seems to be working (at least for me) after upgrading the app to 6.2.18.
Thank you!
