### ISSUE TITLE
Segfault in VECburg

### ISSUE THREAD

**Issue by YannickJadoul** [praat/praat#1599]
When passing a vector of length 1 to `VECburg`, things crash, because of this line (probably messing up the address of the pointer to array stored in `autoVEC b2 = zero_VEC (n);`:

https://github.com/praat/praat/blob/9d1303a5441b73d3c3ffa3601ff6b027b870f822/dwsys/NUM2.cpp#L1459

This seems to happen when using `Sound: To Formant (burg)...` on a `Sound` object with only 2 samples? (See YannickJadoul/Parselmouth#45 for context)
Yes, agreed, this is an invalid use case, getting formants out of 2 samples, but getting UB/segfaults isn't really optimal either.

**Comment by davidweenink** [comment]
Thank you. I will correct this issue.

**Comment by YannickJadoul** [comment]
That's great; thank you!
