### ISSUE TITLE
Typo in paste history in script window

### ISSUE THREAD

**Issue by sanderginn** [praat/praat#160]
Hi,

When adding a point to a PitchTier through the interface and then pasting the action history in the script window, the action is erroneously pasted as
`Add point at: 0.0, 120`

However, this will not run: the working command is
`Add point: 0.0, 120`

**Comment by jjatria** [comment]
I cannot reproduce this on my setup. What version of Praat are you using? What operating system?

Running Praat 6.0.11 on a machine running Kubuntu (15.10 32-bit), the correct command is pasted from the command history.

**Comment by PaulBoersma** [comment]
"Add point..." is a command in the Objects window for a selected PitchTier. "Add point at..." is a command in the PitchTier window, where it contrasts with "Add point at cursor". So you chose the menu command in the PitchTier window, then tried to run it in the Objects window. Either use "Add point..." there (from the Modify menu), or create a script in the PitchTier window. See Scripting chapter 7 in the manual.
