### ISSUE TITLE
can it be used tensorflow or pytouch?

### ISSUE THREAD

**Issue by VegetableWithChicken** [praat/praat#1610]
i want to train to  100% simulation sound of someone by tensorflow or pytouch;
so, what should i label something by praat , i just can use the annotate-TextGrid(sentence) button and get the 'sounding' and 'slient' lable,
so ,it is enough to finished my research? if not , and what should i add？

**Comment by PaulBoersma** [comment]
this question is outside the scope of these "issues". Please refer to the Praat User List instead (and then make it more specific).
