### ISSUE TITLE
Multi-licensing to make App Store usage easier?

### ISSUE THREAD

**Issue by msaehn** [praat/praat#1641]
Hi, there are some issues with GPL license when you want to use it for the iOS app store [1]. Some prominent software using a second license to make this easier possible (like VLC with the MPL 2.0).
Is there any idea to make this possible for praat too?

The easiest license would be probably the MIT/BSD License, but this would remove the copyleft idea.

What do you think about it? (I'm aware that licensing is probably not our favorite topic).
Thank you.

[1]:
* https://github.com/signalapp/Signal-iOS/issues/155
* https://github.com/deltachat/deltachat-ios/issues/41
* https://github.com/nextcloud/ios/blob/master/COPYING.iOS

**Comment by PaulBoersma** [comment]
Licensing is a fine topic, but Praat contains third-party software that was distributed under the GPL, so we cannot supply any lighter licenses for the whole of Praat.
