### ISSUE TITLE
Feature request (with implementation): Additional Keyboard Shortcut for scripting window

### ISSUE THREAD

**Issue by dantheman39** [praat/praat#172]
Hello! I hope that it is socially acceptable to post something like this here, I'm not yet a frequent user of GitHub. 

I love using an external editor for scripting, and see no harm in adding a keyboard shortcut to the "Reopen from disk" command in the File menu of the Scripting editor. I cloned the repo, added this line, compiled, and it's working great for me. I hope you think it's a good idea to add this to the master branch? It's makes a keyboard shortcut of Shift + (command key/control key) + R.

sys/TextEditor.cpp line 606 is:        
          
Editor_addCommand` (this, U"File", U"Reopen from disk", 0, menu_cb_reopen);

I suggest that it be:

Editor_addCommand (this, U"File", U"Reopen from disk", GuiMenu_SHIFT + 'R', menu_cb_reopen);

Again, I apologize if this isn't the place for this, but the change is so trivial I thought it wouldn't hurt to ask.

Dan

**Comment by dantheman39** [comment]
Ok, maybe Shift control O would be better...

**Comment by jjatria** [comment]
> Ok, maybe Shift control O would be better...

+1

**Comment by PaulBoersma** [comment]
To me this destructive command feels like an emergency measure, not something you do all day, so it may not make sense to give it a shortcut. Otherwise, Shift-Command-O it will be, but I think there should also be a warning that all changes will be undone. Please comment.

**Comment by drammock** [comment]
:+1: I also use "reopen from disk" often, because external editors have useful facilities (missing from praat's internal editor) which I like: syntax highlighting, code snippets, etc., but when I'm writing a new praat script (or debugging) I often want to run just one or a few lines of code rather than the whole script (so it doesn't make sense to run the whole script from a bash shell).

**Comment by dantheman39** [comment]
My thoughts are the same as @drammock 's.

As to giving a warning, in my ideal world there would be a pop up with a warning (and hitting enter would mean "ok"), and there would be a check box where one could choose "Don't show again".

**Comment by jjatria** [comment]
In my ideal world Praat's editor would be an instance of [katepart](https://kate-editor.org/about-katepart/), which will soon [ship with syntax highlighting for Praat](https://git.reviewboard.kde.org/r/128905/).

More seriously, I also agree with @drammock: I normally write in an external editor, and use the internal editor mostly for executing or debugging some scripts. So this behaviour does seem desirable, at least for scripters.

**Comment by PaulBoersma** [comment]
OK, good that I asked. So the major use case is when you have an external editor. Then we'll have Shift-Command-O, with a confirmation dialog only in cases where there were changes to the text in Praat's editor (for that majority of users who do use Praat's editor for editing).
