### ISSUE TITLE
GCC 11 build errors: 'numeric_limits' is not a member of 'std'

### ISSUE THREAD

**Issue by brechtsanders** [praat/praat#1739]
There are multiple errors when building with GCC 11:
```
error: 'numeric_limits' is not a member of 'std'
```
The reason why this fails is explained here: https://gcc.gnu.org/gcc-11/porting_to.html#header-dep-changes

After adding `#include <limits>` at the top of `melder/melder.h` building succeeds.

**Comment by imsedgar** [comment]
See pull request #1622
