### ISSUE TITLE
Unit test commandReturns.praat hangs

### ISSUE THREAD

**Issue by rlaboiss** [praat/praat#1753]
After compiling Praat version 6.1.44, the unit test commandReturns.praat hangs forever:

```
$ cd test/
$ ../praat --run ./script/commandReturns.praat 
72 (value in column 8 of row 9)
…
```
A Control-C is needed here in order to interrupt this never-ending command.

It works though with `praat_nogui`:

```
$ ../praat_nogui --run ./script/commandReturns.praat 
72 (value in column 8 of row 9)
0 Pascal0 Pascal
0 Pascal
0 Pascal
$
```

Does anyone knows the reason for this behavior?

**Comment by PaulBoersma** [comment]
I cannot reproduce this with 6.1.51. Can you? If so, which exact edition?

**Comment by rlaboiss** [comment]
It works for me with version 6.1.51. I am hereby closing this issue.
