### ISSUE TITLE
subtract mean bug starting from version 6.1.43

### ISSUE THREAD

**Issue by beqabeqa473** [praat/praat#1766]
Hello devs.

starting from version 6.1.43, i am getting an error in subtract mean.

script i am using is from RHVoice project.
script is located at https://github.com/RHVoice/RHVoice/blob/master/src/scripts/general/import.praat

an error text is the following.

Error: The command "Subtract mean" does not return anything; not assigned to the numeric variable "
speech".
Script line 73 not performed or completed:
« speech=Subtract mean »
Script “/home/voicetrain/rhvoice/src/scripts/general/import.praat” not completed.
Praat: script command <</home/voicetrain/rhvoice/src/scripts/general/import.praat /home/voicetrain/
wav/0001.wav /home/voicetrain/workspace24000/data/wav/RHVoice_0001.wav /home/
voicetrain/workspace24000/data/raw/RHVoice_0001.raw 24000 0 -30>> not completed.

**Comment by davidweenink** [comment]
This is not an issue for Praat. the assignment "speech=Subtract mean" is wrong because "Subtract mean" modifies an object and does not produce a new one. Consult the developes of  RHVoice.

**Comment by beqabeqa473** [comment]
yes, but it worked earlier.

maybe it should be somehow changed? i mean praat script

On 6/11/21, davidweenink ***@***.***> wrote:
> Closed #1766.
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/praat/praat/issues/1766#event-4878930633


-- 
with best regards Beqa Gozalishvili
Tell: +995593454005
Email: ***@***.***
Web: https://gozaltech.org
Skype: beqabeqa473
Telegram: https://t.me/gozaltech
facebook: https://facebook.com/gozaltech
twitter: https://twitter.com/beqabeqa473
Instagram: https://instagram.com/beqa.gozalishvili

**Comment by davidweenink** [comment]
The script that you are using has the line "id = Subtract mean" which has been added recently by one of the developpers. It should read "Subtract mean" instead and in the following line(s) where you refer to this "id" it should be the id of the sound on which Subtract mean works.

Greetings,

David
________________________________
