### ISSUE TITLE
LPC - "Up from Matrix"

### ISSUE THREAD

**Issue by taubaaron** [praat/praat#1800]
Hi,
Until now we have been using different audio files (human singing, no accompany) and conveying "To LPC" (specifically we are using "burg" option but that is not a must). 
After receiving the "LPC Object" we used the option of "Down To Matrix".
What we would like to know is if there is an option to do the opposite action: from a matrix (or "lpc matrix") convert it to lpc (what might be called something like "up from matrix")?
alternitavely, is there a way to reach values of the lpc matrix while still viewing only the lpc object and not converting down to matrix?
TIA

**Comment by PaulBoersma** [comment]
"Down to" means that we are losing information, so the inverse procedure is not necessarily possible.

To see what is in an LPC, use Inspect or save it to a text file.
