### ISSUE TITLE
Create TextGrid via script (Praat crashes)

### ISSUE THREAD

**Issue by pb05061967** [praat/praat#1805]
Hallo, 

if I run this script:

   Create TextGrid: 0, 1, "Mary John bell", "bell"

Praat crashes. It works as expected if I run the same command via GUI.

My system is Windows 10 Home.

All the best, Paolo

**Comment by fncokg** [comment]
It works well on my Praat with Windows 10 Home.

**Comment by PaulBoersma** [comment]
You didn't mention the Praat version, so I assume the bug has gone. Re-open if not.
