### ISSUE TITLE
Just out of curiosity, what are the meanings of the folder names such as fon and melder etc. ?

### ISSUE THREAD

**Issue by kgco** [praat/praat#1835]
I see that many main functions are defined in the files under the `fon` folder and the main output functions are defined in the `melder` folder and all the functions have the prefix `Melder_` such as `Melder_throw()`.

Just out of curiosity, what are the meanings of the names?

**Comment by PaulBoersma** [comment]
fon = phonetics (in contrasts with stat = statistics, or gram = grammar)
Melder is a Dutch word meaning messenger; it does messaging, and a bit more
