### ISSUE TITLE
Sound editor redraw fails occasionally

### ISSUE THREAD

**Issue by drammock** [praat/praat#184]
With Praat 6.0.14 (64 bit, Xubuntu), I hit an issue this morning where the sound editor was not responding to mouse (click-drag to make selections) or keyboard (zooming commands like Ctrl+i, Ctrl+a, etc) commands.  The commands were clearly registering, but the redraw to reflect the commands would not occur until I clicked outside the editor window (or pressed Alt+Tab) such that the editor window lost system focus (at which point if I had, say, click-dragged a selection and pressed Ctrl+n, the window would correctly show the waveform zoomed in to the selection I had made).  The redraw would occur when the editor lost focus, not when focus returned to the editor.  This happened only in one out of several sound editor windows this morning; closing that editor and re-opening from the same object in the list failed to reproduce.  If it happens again, is there anything I should do / try to help narrow down the cause?

**Comment by PaulBoersma** [comment]
OK, this was some time ago. Does it still happen?

**Comment by drammock** [comment]
I did some quick testing with 6.0.21 and couldn't reproduce, but then again I haven't been using praat much in the last couple months and it was a sporadic error, so I can't say for sure that it's gone away.

**Comment by drammock** [comment]
closing due to failure to replicate / my lack of motivation to track down the root cause.  If it crops up again I'll re-open.
