### ISSUE TITLE
Praat Objects window

### ISSUE THREAD

**Issue by UndescriptDev** [praat/praat#1886]
![Screenshot from 2021-09-25 17-18-30](https://user-images.githubusercontent.com/80742709/134787348-7f577388-b344-4d91-8260-131569306215.png)

**Comment by PaulBoersma** [comment]
That looks interesting. Can you guide us toward replicating this problem? To start with: what was the Praat version, and what was the operating system?

**Comment by UndescriptDev** [comment]
OS: Arch Linux (technically it is Anarchy Linux which is just Arch Linux with an install script added to it.)

Version: Praat 6.1.52 (August 25 2021)

I don't know how to explain how to replicate it. The Praat window was like this when I compiled from source and also from installing from a repository called arch4edu (I am using Praat from the repo). Here is the output when I run Praat in the terminal if it helps: (praat:12751): Gdk-WARNING **: 10:28:40.218: ../gtk/gdk/x11/gdkwindow-x11.c:5653 drawable is not a native X11 window

**Comment by UndescriptDev** [comment]
I logged into my system with gnome on xorg instead of using wayland, and everything is okay.

**Comment by rotsee** [comment]
As more and more distros migrate away from the X11, this might be worth fixing. For the average user, the Praat version installable from e.g. Ubuntu's software center now appears broken (unless you are tech savvy enough to find this bug report, and switch to a different window manager... )

**Comment by PaulBoersma** [comment]
I solved this during the last week. You can expect version 6.2 tomorrow, which works fine under Wayland (as well as again on a Chromebook).
