### ISSUE TITLE
Compiling on Macintosh

### ISSUE THREAD

**Issue by thomasokken** [praat/praat#190]
I would like to build Praat on OS X, but I'm falling at the first hurdle.
The instructions in README.md start with

    Extract the *xcodeproj64.zip* file from the latest release

but where do I find this xcodeproj64.zip file? It's not in the praat-master.zip file that I downloaded, and I don't see it when I do a git clone either.

**Comment by jjatria** [comment]
You can find it in the [releases](https://github.com/praat/praat/releases) page.

For example, here's the link to [the latest 64-bit release](https://github.com/praat/praat/releases/download/v6.0.14/praat6014_xcodeproj64.zip).

**Comment by thomasokken** [comment]
Thank you!
