### ISSUE TITLE
Textgrid that includes transcriptions won't open

### ISSUE THREAD

**Issue by blru2021** [praat/praat#1901]
Hello,

I finished the transcription of a sound file and saved the textgrid as a textfile in the same folder as the sound file, as usual. However, this time praat was not closing immediately after my command. I stopped the program to try and reopen and save the file again but now the textgrid file won't open. Here's the error message. Could you please let me know if I can save the file or do I have to redo the transcriptions?

Thanks!

<img width="304" alt="Praat error" src="https://user-images.githubusercontent.com/87008344/138430365-282db23f-7351-4151-8b1d-513f3e488b1a.png">
?

**Comment by PaulBoersma** [comment]
What you probably did was to save the Sound and the TextGrid _together_ as a text file. The result would be a large file, so large that out of impatience you probably forced-quit Praat ("stopped the program", as you say), while it was still saving the data. So the resulting file was probably incomplete, i.e. broken off at line 13,194,726. From the message it is clear to me that you forced-quit Praat while it was still saving the Sound, and that no TextGrid data has been saved.
