### ISSUE TITLE
Infinite loop in "Change gender"

### ISSUE THREAD

**Issue by YannickJadoul** [praat/praat#1926]
I got an issue reported at YannickJadoul/Parselmouth#68 by @auspicious3000, that in some cases, "Change gender"'s execution blocks.

@auspicious3000 very kindly provided me an minimal reproducing example of a case in which this happens, and it seems that the error lies somewhere in Praat, as I can reproduce the issue in Praat.

The following should reproduce the error (tried out in Praat 6.1.51, and in the latest `master` version):
- Read the FLAC file in this zip file into Praat: [2552-132097-0069.zip](https://github.com/praat/praat/files/7538443/2552-132097-0069.zip)
  *(Apologies for the zip file, but GitHub only allows to upload certain file types/extensions into an issue.)*
- Run "Change gender", with parameters: 50, 250, 0.79, 105.469, 1.487, 1.0
- Praat hangs and gets into an infinite loop.

I've compiled a debug version of Praat and found out the following:
- According to my debugger, the infinite loop happens at https://github.com/praat/praat/blob/586bc8b05a9d3d3dcff45a3da63882516773c13c/fon/Manipulation.cpp#L418 as endOfTargetNoise is +inf.
- endOfTargetNoise is +inf, because of a division by zero at https://github.com/praat/praat/blob/586bc8b05a9d3d3dcff45a3da63882516773c13c/fon/Manipulation.cpp#L399

I haven't looked further than this, trying to figure out why `RealTier_getValueAtTime (pitch, endOfSourceVoice)` on line 399 results in 0. If I do figure out more, I will update!

**Comment by PaulBoersma** [comment]
For this example, Praat 6.2.02 will bail out with an appropriate error message, which is "Change gender: your pitch manipulation would lead to negative pitch values."  Thanks for the excellent bug hunt.

**Comment by YannickJadoul** [comment]
Thank you for solving this!

One small additional question: in older versions of Praat (before the 6.2.02 fix), is there a way of detecting when this would happen, in order to not call "Change gender" on this audio with these parameters, and avoid getting stuck in this infinite loop?

**Comment by PaulBoersma** [comment]
Instead of "Sound: Change gender", you could compute the pitch yourself (with the given minimum and maximum pitch) and do "Sound & Pitch: Change Gender". Once you have the Pitch, you can query its minimum (without interpolation) and median, and check whether the resulting pitch value will be less than 0:

    scaledMinimum = minimum * newMedian / median
    resultingMinimum = newMedian + (scaledMinimum - newMedian) * pitchRangefactor
    if (resultingMinimum <= 0.0) ...

**Comment by YannickJadoul** [comment]
Thank you very much! This will be quite useful to @auspicious3000.
