### ISSUE TITLE
Bug - Scripting - infile, outfile and folder - browse buttons are not displaying properly - Praat 6.2.04

### ISSUE THREAD

**Issue by rolandomunoz** [praat/praat#1975]
In the release  ``` 6.2.04``` I found that the browse buttons for `infile`, `outfile` and `folder` fields are not displaying properly in Windows 10.
![image](https://user-images.githubusercontent.com/18198623/147389610-94ed82cc-4bee-4c35-89d5-0aba43f4da39.png)

I run this little test.
```
form Test
  infile Source_path
  outfile Destiny_path
  folder Dir
endform

writeInfoLine: source_path$
appendInfoLine: destiny_path$
appendInfoLine: dir$
```

Here is my computer info:

- OS: Windows 10 Pro (version 21H2)
- Processor: Intel(R) Core(TM) i5-5300U CPU @ 2.30GHz   2.29 GHz
- Praat version: 6.2.04 (64 bits)

Thank you!

**Comment by PaulBoersma** [comment]
yuck, will repair
