### ISSUE TITLE
OSX: keyboard interaction broken

### ISSUE THREAD

**Issue by psibre** [praat/praat#200]
I'm used to confirming the quit dialog by just hitting the enter key.
![quit](https://cloud.githubusercontent.com/assets/1278639/14353246/871caae0-fcd8-11e5-8526-edf64adc109a.png)
This worked on OSX right up until v6.0.11.
However, from v6.0.12 onwards, hitting enter no longer works.

~~More critically however, any keyboard interaction, such as tabbing through elements in a form or dialog, is broken and causes Praat to crash (at least on 10.9.5).~~

**Comment by psibre** [comment]
Sorry, the second part of this issue was fixed in 6.0.14 of course. Updating above.

**Comment by PaulBoersma** [comment]
Confirmed. A Mac-only problem. Will fix.

**Comment by PaulBoersma** [comment]
Fixed in 6.0.21.
