### ISSUE TITLE
Erratic behaviour: only indexed variables can't share function names

### ISSUE THREAD

**Issue by jjatria** [praat/praat#201]
Normally, it's not a problem that variables and functions have the same names (which is definitely a good thing):

~~~praat
string$ = "hello"
appendInfoLine: string$

index = 1
appendInfoLine: index
~~~

But _indexed_ variables seem to be an exception:

~~~ praat
string$[1] = "hello"
asserterror Expected the end of the formula, but found "["
appendInfoLine: string$[1]

right$[1] = "hello"
asserterror Unknown variable:
appendInfoLine: right$[1]

# Same with numeric functions
index[1] = 1
asserterror Unknown variable:
appendInfoLine: index[1]
~~~

Is this a desired behaviour? I would understand if variables could _never_ be named like functions. But the fact that some of them can, and some of them cannot, is confusing.

It's also confusing that the error is raised when the variable is used, and not when it is assigned. If those variable names are invalid, then surely the error should be caught sooner?

**Comment by PaulBoersma** [comment]
I just repaired this. Both numeric and string function names can be used for indexed variables.
