### ISSUE TITLE
Release tag prefixes

### ISSUE THREAD

**Issue by alerque** [praat/praat#2024]
Was the switch to unprefixed semver tags with `2.6.11` (from `v` prefixed tags like `v2.6.10`) intentional or a slip? It usually doesn't matter a whole lot either way, but being consistent one way or the other does matter for downstream tooling...

**Comment by alerque** [comment]
Apparently it was accidental, because we're back to v prefixes with `v2.6.12`. Just so you know, a commit can be tagged more than once so you could add in the now missing sequence `v2.6.11` tag without removing the off-pattern one many were forced to use.

**Comment by PaulBoersma** [comment]
OK, I corrected this. In the list of releases, Praat 6.2.11 now appears above 6.2.13, though.

**Comment by alerque** [comment]
It's okay. The default release page is chronological not semver sorting, but most distros that watch tags handle semver sorting just fine. Also the things like GitHub's `latest` release URL shortcut and flag work on semver, not time. After a release or two it won't even be noticed.

**Comment by ldo** [comment]
I cloned the repo recently, and I notice the `v6.2.11` tag is pointing to the same release as `v6.2.14`, 68e1ce141b130b634927cfeeca44210f10540088. Shouldn’t it be pointing to the `6.2.11` one 5d633a9ddb63f1894055897e056b75e932f4218e instead?
