### ISSUE TITLE
Problems with interval aligner

### ISSUE THREAD

**Issue by jjatria** [praat/praat#203]
The interval aligner does not currently work in Linux (Kubuntu 15.10, 32-bit). In 6.0.15 it creates empty intervals, and in 6.0.16 it crashes Praat with a message about non-matching sampling rates.

See [the thread on the mailing list](https://uk.groups.yahoo.com/neo/groups/praat-users/conversations/topics/7656) for more details.

As requested, @PaulBoersma

**Comment by PaulBoersma** [comment]
This bug surfaced on Windows 32-bit and Linux 32-bit. Solved in 6.0.17.
