### ISSUE TITLE
Praat 6.2.15 - TextGridEditor - Sound part is blue in the SoundEditor and black in TextGridEditor

### ISSUE THREAD

**Issue by rolandomunoz** [praat/praat#2193]
Operating system: Windows 10 (64 bits)
Praat version: praat6215_win64

The sound part in the `SoundEditor` is blue.
![image](https://user-images.githubusercontent.com/18198623/185187701-1cb76e64-20d0-4e57-9874-8f5c77699aa2.png)

But, it is black in the `TextGridEditor`
![image](https://user-images.githubusercontent.com/18198623/185187651-5014ade4-d663-4d42-96ab-76ee99a76e2c.png)

**Comment by PaulBoersma** [comment]
yes, modifiable stuff is in dark blue and non-modifiable stuff is in another colour, usually black. Now we just have to document this better, and make the pitch curve colour distinct enough.
