### ISSUE TITLE
Praat 6.2.16: test/fon/LongSound.praat breaks automatic testing by test/runAllTests_batch.praat

### ISSUE THREAD

**Issue by imsedgar** [praat/praat#2197]
test/runAllTests_batch.praat calls test/fon/LongSound.praat which contains the line

> View & Edit

which cannot executed in batch mode. The error is

> Error: Cannot view or edit a TextGrid from batch.

which stops the tests with error:

> Praat: script command <<runAllTests_batch.praat>> not completed.

The batch test script test/runAllTests_batch.praat should not call the line that causes the error.

**Comment by imsedgar** [comment]
The fix is as simple as putting a "# " in front of "View and Edit". Should I create a pull request, or can you directly fix it?

**Comment by PaulBoersma** [comment]
Well, that's not the fix. Instead, this part of the LongSound test should move to a script with the name "_GUI" in it.

**Comment by PaulBoersma** [comment]
repaired on September 17

**Comment by imsedgar** [comment]
Sorry, this isn't repaired.
The script test/runAllTests_batch.praat excludes files with includes "_GUI_" in there filename. But you named the script [LongSoundEditor_GUI.praat](https://github.com/praat/praat/blob/master/test/fon/LongSoundEditor_GUI.praat), but it should be LongSoundEditor_GUI_.praat .

**Comment by PaulBoersma** [comment]
You are right of course. Now corrected, sorry.
