### ISSUE TITLE
Linux audio playback cuts off after about 1 second

### ISSUE THREAD

**Issue by Linguista** [praat/praat#2201]
Linux audio playback always cuts off after about one second. This happens on the latest Praat (6.2.16), and was also happening on versions at least as old as the April 2022 ones. This makes the program unusable.

This happens regardless of how I try and play the audio -- from the Objects window with `Play part...` on a LongSound, from the Objects window with `Play` on a Sound object, from the editor window with and without a TextGrid using the TAB button or any of the sound playing buttons at the bottom, etc.

It also happens regardless of what sound output device I use, be it speakers, headphone or BT headphone.

_ADDENDUM: The above was done with Praat set to use the default sound system. I think it was Pulse Audio. I switched it to PortAudio/ALSA to test it and the audio played for more than about a second, but when Praat reached the end of the selection it crashed, and now it crashes every time I try to open it. (This is why I can't confirm what the selected sound system was originally)._

Info on my computer is provided below. I deleted three audio devices which I don't use.

**SYSTEM INFORMATION**
```
    System:
    Kernel: 5.18.17-200.fc36.x86_64 arch: x86_64 bits: 64 compiler: gcc
        v: 2.37-27.fc36 Desktop: KDE Plasma v: 5.25.4 tk: Qt v: 5.15.5 wm: kwin_x11
        dm: SDDM Distro: Fedora release 36 (Thirty Six)
    Audio:
        Device-2: AMD Starship/Matisse HD Audio vendor: ASUSTeK
        driver: snd_hda_intel v: kernel pcie: speed: 16 GT/s lanes: 16
        bus-ID: 0d:00.4 chip-ID: 1022:1487
        Device-4: Audient iD4 type: USB driver: hid-generic,snd-usb-audio,usbhid
        bus-ID: 1-2.3:13 chip-ID: 2708:0009
      Sound Server-1: ALSA v: k5.18.17-200.fc36.x86_64 running: yes
      Sound Server-2: PulseAudio v: 15.0 running: no
      Sound Server-3: PipeWire v: 0.3.56 running: yes`
```

**Comment by davidweenink** [comment]
This happens because of the pipewire  emulation of pulseAudio.  I have not yet found out how to get it right on pipewire. The recipe for now is to  remove pipewire and have pulseAudio do the sound serving.

**Comment by Linguista** [comment]
Thanks very much.

**Comment by PaulBoersma** [comment]
There was a Pipewire update that solved this problem.
