### ISSUE TITLE
Releases crosswired

### ISSUE THREAD

**Issue by alerque** [praat/praat#2207]
The latest release which was just tagged was expected to be 6.2.18, and that's even what the release title says, but the *tag* was posted as 6.2.22

https://github.com/praat/praat/releases/tag/v6.2.22

**Comment by alerque** [comment]
Will there be any attempt to fix this? Can you at least let us know what the plan is so distributions can step forward appropriately? Will there be an actual 6.2.18 tag we should pull from? Or should the source code in the current bogus code be patched so it identifies as 6.2.22 internally? Will the next release by `.19` or `.23`? Even if no action is taken knowing what the project's next move will be will help distros figure out how to package this snafu.

**Comment by PaulBoersma** [comment]
I sort of repaired this now, sorry for the misnumbering. The source code is one not-so-important commit further than the binaries. The tag is now 6.2.18, and the next version will be 6.2.19.

**Comment by alerque** [comment]
Thanks! Armed with that information I've updated the Arch Linux AUR packages (both [source build](https://aur.archlinux.org/packages/praat) (using the new correct tag) and [binary blob wrapper](https://aur.archlinux.org/packages/praat-bin) (by relabeling the 6.2.22 debian package)) to 6.2.18. Thanks for letting us know what the plan for future version numbering is.
