### ISSUE TITLE
Release is tagged v6.2.22, but title says 6.2.18

### ISSUE THREAD

**Issue by imsedgar** [praat/praat#2208]
praat version 6.2.18 is released with tag v6.2.22:
https://github.com/praat/praat/releases/tag/v6.2.22

**Comment by alerque** [comment]
Duplicate of #2207.

**Comment by imsedgar** [comment]
@alerque Yes, #2007 describes the same problem. But sorry, I didn't see your issue, your title is too less descriptive.

**Comment by PaulBoersma** [comment]
OK, I sort of repaired this now.
