### ISSUE TITLE
Some voices on Mac OS X only 'whispering' the trasients, not actually speaking

### ISSUE THREAD

**Issue by NeuroNoNeuro** [praat/praat#2215]
Per the title - the words on some voices come out as a whispering transient sound.

For example, "This is some text", using English (America), Voice variant: Adam.

![Screen Shot 2022-09-18 at 2 30 44 PM](https://user-images.githubusercontent.com/38725630/190928803-949fd0f1-40b6-4b73-a913-fb61c4022a0d.jpg)

Happens with a few voices, no explanation as to why, or what to fix to make it actually work

Mac OS X Monterey, 12.6

**Comment by PaulBoersma** [comment]
This was repaired for version 6.3.18 (October 2023).
