### ISSUE TITLE
[macOS] version 6.2.23 invalidly code-signed

### ISSUE THREAD

**Issue by core-code** [praat/praat#2237]
previous releases were properly signed with a 'Developer ID' codesignature [1], but the new release 6.2.23 contains a invalid "Apple Development" code-signature [2] that is not meant for distributing downloadable software. The "Apple Development" certificates are only meant for uploading software to Apple to have it distributed on the Mac App Store. because the wrong certificates have been used for signing, launching the app cannot be done without disabling gatekeeper.

[1]: `Developer ID: Paul Boersma (J9C6R9XA5W) `
[2]: `Apple Development: Paul Boersma (99U28X6B6F)`

**Comment by PaulBoersma** [comment]
The distribution for 6.2.23 was repaired as soon as I heard of it on October 10. Thanks.
