### ISSUE TITLE
File test/fon/closeEditor_GUI.praat should be renamed to test/fon/closeEditor_GUI_.praat

### ISSUE THREAD

**Issue by imsedgar** [praat/praat#2280]
File `test/fon/closeEditor_GUI.praat` should be renamed to `test/fon/closeEditor_GUI_.praat`.

`praat-6.3.02.tar.gz` contains file `praat-6.3.02/test/fon/closeEditor_GUI.praat` which doesn't match the syntax of script `praat-6.3.02/test/runAllTests_batch.praat` which tries to exclude GUI tests. This script excludes files with name `\_GUI\_`, but this doesn't match `closeEditor_GUI.praat`.

`praat --run runAllTests_batch.praat` stops with error

```
### executing ./fon/closeEditor_GUI.praat:
Error: Cannot edit a Sound from batch.
Script line 3 not performed or completed:
« View & Edit »
Script “/builddir/build/BUILD/praat-6.3.02/test/./fon/closeEditor_GUI.praat” not completed.
Formula not run.
Script line 52 not performed or completed:
« runScript: .filePath$ »
Script “/builddir/build/BUILD/praat-6.3.02/test/runAllTests_batch.praat” not completed.
Praat: script command <<runAllTests_batch.praat>> not completed.
```

**Comment by PaulBoersma** [comment]
Thanks, repaired now.
