### ISSUE TITLE
null flush option for executable

### ISSUE THREAD

**Issue by jonorthwash** [praat/praat#230]
Instead of using `--run`, it would be nice to have a way to directly feed scripts to a running console-mode version of the executable.  Using such an approach, a script could open the executable once, pipe commands to it, and send a null character to flush the buffer.  This would make using Praat from an external script (such as with [PraatR](https://github.com/usagi5886/PraatR)) much faster.

**Comment by jonorthwash** [comment]
Note that this would be more or less like using sendpraat, but the gui would not have to be open.

**Comment by PaulBoersma** [comment]
The following should work again: `yourProgram | praat -`
