### ISSUE TITLE
[Linux musl] melder/melder_real.h: build fails in GCC 12 with "numeric_limits is not a member of std'

### ISSUE THREAD

**Issue by andrewathalye** [praat/praat#2304]
This is caused by the same issue that caused problems earlier with GCC 11, and reproduces on linux x86_64 on musl libc. It can be fixed just by adding "#include <limits>" to the top of melder_real.h. The build succeeds on that platform otherwise. I don't currently have the ability to check if this error occurs with glibc, but it is probable.

**Comment by PaulBoersma** [comment]
This is not enough information for us to figure out what could be going on. Can you at least specify the exact compilation line that gave you this error? For instance, did you include the required option `-std=c++17`?

**Comment by PaulBoersma** [comment]
#include &lt;limits&gt; was included in Melder.h before Melder_real.h, already on 11 June 2021. A newer version of the source code may solve your problem.

**Comment by andrewathalye** [comment]
You are correct, it looks like my distro bundles Praat 6.1.42 and a fresh build from trunk does not reproduce the same issue. Sorry for the extraneous bug report.
