### ISSUE TITLE
sys/praat.cpp - praat_cleanUpName - Why replacing ` ` and `.` characters by underscores?

### ISSUE THREAD

**Issue by rolandomunoz** [praat/praat#2321]
Dear Paul:

I would like to ask you if there is a reason to replace blank spaces (` `) and the dot `.` characters by underscores within the `praat_cleanUpName()` function. As far as I'm concerned, those characters are valid in the filenames across many operating systems.

sys/praat.cpp
```
void praat_cleanUpName (char32 *name) {
/*
	Replaces spaces and special characters by underscores.
*/
	for (; *name; name ++)
		if (str32chr (U" ,.:;\\/()[]{}~`\'<>*&^%#@!?$\"|", *name))
			*name = U'_';
}
```

Thank you in advanced!

**Comment by PaulBoersma** [comment]
One historical reason is that one can still refer to objects by name in scripts, as in

    Sound_hello_world [col - 1]

(there are several more cases when using pre-2014 syntax).

For file names avoiding spaces is indeed (no longer?) necessary when saving files. However, corpora usually avoid spaces, so as not to run into problems with shell scripts that like to open those files (in shell scripting languages, spaces tend to be used as argument separators). It is good practice in academic work that involves collections of files to not use spaces in their names. Even if Praat and R and Python and Matlab no longer care much, there are still those other languages that will get confused.

Anyway, we would probably break existing code if we changed this now, so we continue to nudge users toward not using spaces in file names, although we do support them.

**Comment by PaulBoersma** [comment]
As for the period (.), it is not so long ago that an operating system called Microsoft Windows would get confused about extensions, if file names contained two periods, and we all know about problems with files named `pictures.docx.exe` if the user hasn’t switched off “hide extensions”. Here as well, we continue to nudge users toward not using periods in file names, although we do support periods and spaces if the user types them when saving, or if a script creates files with such names.

**Comment by rolandomunoz** [comment]
Thank you for your response! I work with sound files that cannot be renamed because of legal restrictions. They usually come with dots and spaces, so I always had this question. Now it is clear to me.
