### ISSUE TITLE
(Feature Request): Rule for Make Install

### ISSUE THREAD

**Issue by meyersbs** [praat/praat#242]
Can you please write a rule for make install?

**Comment by PaulBoersma** [comment]
What should "make install" do exactly? Move the executable somewhere else, I guess, but where? Into a place accessible to all users, e.g. installing it to `/usr/sbin` by using `sudo`?

**Comment by meyersbs** [comment]
``` make install ``` should put the executables into ``` /usr/bin ```.

**Comment by PaulBoersma** [comment]
So that would be simply `sudo mv praat /usr/bin` in your case, but perhaps something different in other people's cases, unless you can convince me that `/usr/bin` is the place where executables should generally go.

**Comment by meyersbs** [comment]
In a Linux file system, the standard conventions are:
- ``` /usr/bin ``` is for executables installed by a package manager (apt, yum, etc.).
- ``` /usr/sbin ``` is essentially the same as ``` /usr/bin ```, except that executables in ``` /usr/sbin ``` generally require root privileges to run.
- ``` /usr/lib ``` is for libraries (which aren't already installed) that libraries depend on.
- ``` /bin ``` and ``` /sbin ``` are for OS-specific core functions, such as ``` chmod, fsck, iptables, etc ```.
- Note: ``` /sbin ``` doesn't exist in many older distributions.

In this case, I was slightly wrong; the ``` make install ``` rule should put the Praat executables in ``` /usr/local/bin ```  and libraries that Praat depends on should go in ``` /usr/local/lib ```, as package managers will not touch things in ``` /usr/local ```.

When installing via ``` sudo apt-get install praat ``` executables should be put in ``` /usr/bin ``` and libraries should be put in ``` /usr/lib ```.

Source: [Linux Foundation Filesystem Hierarchy Standard](http://refspecs.linuxfoundation.org/FHS_3.0/fhs/index.html)

<hr>

Here is my proposed ``` make install ``` rule:

``` bash
prefix=/usr/local

    install: praat
        install -m 0755 praat $(prefix)/bin
   
   .PHONY: install
```

**Comment by PaulBoersma** [comment]
OK, so done. In `makefile.defs.linux.pulse`:

   INSTALL = install -p praat /usr/local/bin

and in the root `makefile`:

   .PHONY: all clean install
