### ISSUE TITLE
Compilation of praat.cpp fails on i386 with g++ 13

### ISSUE THREAD

**Issue by rlaboiss** [praat/praat#2433]
The autobuild on an i386 system for the praat Debian package [fails](https://buildd.debian.org/status/fetch.php?pkg=praat&arch=i386&ver=6.3.11-1&stamp=1689959453&raw=0) for version 6.3.11.  The previous version (6.3.10) [successfully built](https://buildd.debian.org/status/fetch.php?pkg=praat&arch=i386&ver=6.3.10-2&stamp=1686709016&raw=0).

The sensible difference between these two runs is the fact that the former was built against g++ v12 and the latter against g++ v13.

The error message is the following:
```
Crashing bug: Praat will crash. Please notify the author (paul.boersma@uva.nl) with all of the following information (and please mention in your email precisely what you were doing when this crash occurred):

Assertion failed in file "praat.cpp" at line 2208:
   x3 [2] == 2.718

This error message percolated all the way to the top.
```

I wonder if the code in [line 2207](https://github.com/praat/praat/blob/master/sys/praat.cpp#L2207) of file `sys/praat.cpp` works properly on a 32-bit system.

**Comment by rlaboiss** [comment]
I am currently applying a [patch](https://salsa.debian.org/med-team/praat/-/blob/master/debian/patches/ftbfs-on-i386-with-g%2B%2B13.patch) to the Debian patch, which comments lines 2207 to 2010 in `sys/praat.cpp`.

**Comment by AdrianBunk** [comment]
> The sensible difference between these two runs is the fact that the former was built against g++ v12 and the latter against g++ v13.

Yes, gcc 13 has new excess precision issues in C++ on i386/m68k/s390x.

There are two possible solutions:
- build with `-std=gnu++17` instead of `-std=c++17` (e.g. by appending it to `CXXFLAGS` in `debian/mk-vars-hardening`), or
- add `-fexcess-precision=fast` to `CXXFLAGS`

**Comment by rlaboiss** [comment]
According to the GCC [documentation](https://gcc.gnu.org/onlinedocs/gcc/Optimize-Options.html#index-fexcess-precision), `-fexcess-precision=fast` is the default. Wouldn't the second option (add -`fexcess-precision=fast` to `CXXFLAGS`) be moot?

**Comment by AdrianBunk** [comment]
@rlaboiss The default differs in the "strict conformance" part of the paragraph.

**Comment by rlaboiss** [comment]
@AdrianBunk: I changed the Debian package according to your suggestion (commit [aaf9e43](https://salsa.debian.org/med-team/praat/-/commit/aaf9e4362a0f4c28a8a475bc86fafb271a876714)). The FTBFS is apparently fixed on i386 and the change does not seem to have an impact on amd64. Thanks for the tip!

**Comment by PaulBoersma** [comment]
This is in fact a problem in Praat. The lines

    double a[] = { 3.14, 2.718 };
    assert (a[1] == 2.718);

can and should easily fail. In the assertion line, a[1] has been rounded to double-precision floating-point, and 2.718 can be extended-precision floating-point. This should be normal and expected. I have replaced the example with a number that can be represented exactly in 64-bit and 80-bit floating point, namely 2.717999999999999971578290569595992565155029296875, which is the nearest 64-bit number to 2.718. It's precisely 765048986699563/2^48. Thanks!
