### ISSUE TITLE
errors in praat_sound_init.cpp

### ISSUE THREAD

**Issue by caffeinator13** [praat/praat#253]
I tried to build the program using `make` and I got this.
I'm using Ubuntu 16.04

> praat_Sound_init.cpp: In function ‘void INFO_Praat_reportSoundServerProperties(UiForm, int, Stackel, const char32_, Interpreter, const char32_, bool, void_)’:
> praat_Sound_init.cpp:2156:1: error: ‘END’ was not declared in this scope
>  END
>  ^
> In file included from praat_Sound_init.cpp:19:0:
> ../sys/praat.h:484:157: error: a function-definition is not allowed here before ‘{’ token
>  rm sendingForm, int narg, Stackel args, const char32 *sendingString, Interpreter, const char32 *invokingButtonTitle, bool, void *okClosure) { \
>                                                                                                                                              ^
> praat_Sound_init.cpp:2159:1: note: in expansion of macro ‘FORM_WRITE3’
>  FORM_WRITE3 (SAVE_Sound_saveAsAifcFile, U"Save as AIFC file", nullptr, U"aifc") {
>  ^
> praat_Sound_init.cpp:2770:1: error: expected ‘}’ at end of input
>  }
>  ^
> praat_Sound_init.cpp:2770:1: error: expected ‘catch’ at end of input
> praat_Sound_init.cpp:2770:1: error: expected ‘(’ at end of input
> praat_Sound_init.cpp:2770:1: error: expected type-specifier at end of input
> praat_Sound_init.cpp:2770:1: error: expected ‘)’ at end of input
> praat_Sound_init.cpp:2770:1: error: expected ‘{’ at end of input
> praat_Sound_init.cpp:2770:1: error: expected ‘}’ at end of input
> praat_Sound_init.cpp:2770:1: error: expected ‘}’ at end of input
> <builtin>: recipe for target 'praat_Sound_init.o' failed
> make[1]: *_\* [praat_Sound_init.o] Error 1
> make[1]: Leaving directory 'cppworkspace/praat/fon'
> makefile:14: recipe for target 'all' failed
> make: **\* [all] Error 2

**Comment by PaulBoersma** [comment]
Please try again with the present version. If it does not work, please report exactly what you did to make the problem happen. Did you cp the correct makefile.defs, for instance?
