### ISSUE TITLE
Extraneous files in 6.3.17 tarball

### ISSUE THREAD

**Issue by rlaboiss** [praat/praat#2532]
Two Windows executable files slipped into the 6.3.17 tarball:

```
$ tar tfvz praat_6.3.17.orig.tar.gz | grep exe$
-rw-rw-r-- root/root    257962 2023-09-10 13:33 praat-6.3.17/test/manually/spit/spit win.exe
-rw-rw-r-- root/root    257962 2023-09-10 13:33 praat-6.3.17/test/manually/spit/spit_win.exe
```

Please, remove them in the next release.

**Comment by PaulBoersma** [comment]
These files are there for manual testing (also the Mac versions). Is it bad to have them?

**Comment by PaulBoersma** [comment]
Well, the source code is also there, namely in `spit.c` in the same folder. Does that mean that the executable is allowed as well? For reference, this is the whole source code:
```
#include <stdio.h>
int main (int argc, char **argv) {
	for (int i = 0; i < argc; i ++)
		printf ("arg [%d] = <<%s>>\n", i, argv [i]);
}
```

**Comment by rlaboiss** [comment]
Thanks for pointing it out, I have overseen that file spit.c. Everything is okay. I am hereby closing this issue.
