### ISSUE TITLE
Chromebook Lenovo C330 Help!

### ISSUE THREAD

**Issue by kxd23g** [praat/praat#2579]
Hello! I am taking online courses & am required to download Pratt. Following the download guide for Chromebook, I entered:

uname -a into Linux
instead of getting x86_64 or arm64, I received aarch64 (below)

Linux penguin 6.1.55-06877-gc83437f2949f #1 SMP PREEMPT Thu Dec 14 19:14:17 PST 2023 aarch64 GNU/Linux

I called IT but was referred to seek help here. 
Thank you for any advice!

**Comment by PaulBoersma** [comment]
aarch64 is the same as arm64
