### ISSUE TITLE
[Documentation] Missing setting "Attenuation at ceiling" in documentation

### ISSUE THREAD

**Issue by ivanipenburg** [praat/praat#2602]
Hi,

On the following page:
https://www.fon.hum.uva.nl/praat//manual/Sound__To_Pitch__filtered_ac____.html
or in the docstring in file `fon/manual_pitch.cpp` an explanation for the setting `attenuationAtCeiling` as seen [here](https://github.com/praat/praat/blob/master/fon/praat_Sound.cpp#L1720C12-L1720C32) is missing.

I don't know enough about pitch analysis to add it, but hope this issue is helpful.

**Comment by PaulBoersma** [comment]
OK. The "attenuation at ceiling" is explained under "Algorithm" on that same page, but I should probably add it under "Settings" as well.
