### ISSUE TITLE
Forms: "Only “choice”, “optionmenu” and “boolean” fields can take a number" for real/positive/integer/natural

### ISSUE THREAD

**Issue by djvill** [praat/praat#2643]
On Praat 6.4.12 for Windows x64 Intel, forms throw errors for real/positive/integer/natural depending on syntax. 

Specifically, the following yields `Only “choice”, “optionmenu” and “boolean” fields can take a number: natural: "position", 1`:

```praat
form: "Add tier"
  natural: "position", 1
endform
```

Same goes with `real:`, `positive:`, and `integer:`.

However, all of the following are okay:

```praat
form: "Add tier"
  natural position 1
endform

form: "Add tier"
  natural: "position", "blibla"
endform

beginPause: "Add tier"
  natural: "position", 1
endPause: "Continue"
```

**Comment by PaulBoersma** [comment]
"natural" takes a string, like this:

    natural: "position", "1"

This is because you can add comments in, like so:

    natural: "position", "0 (= at end)"
