### ISSUE TITLE
UTF-8 TextGrid saved as UTF-16

### ISSUE THREAD

**Issue by William-N-Havard** [praat/praat#2662]
I noticed that TextGrid files originally encoded in UTF-8 get saved to UTF-16 (using Ubuntu 22.04.4 LTS and the latest version of Praat).

Would there be a way to prevent that from happening and use the original file encoding ?

**Comment by PaulBoersma** [comment]
There is no way that Praat remembers whether a TextGrid that it has in its list comes from a binary file, a UTF-8 text file, or a UTF-16 text file. Or, for that matter, if your text files were "short" or not. Or came from a chronological file. Or whether the TextGrid object was created with the "New" menu. Or by choosing "To TextGrid..." after selecting a Sound object.

If you want to save your text files as UTF-8 files, go to Praat -> Settings -> Text Writing Settings, and choose "UTF-8". From that moment on, all your text files will be saved as UTF-8, no matter where your text came from. This settings works for any kind of object, as well as for stuff you save from the Info window or from a script window.
