### ISSUE TITLE
FormantPath tracking regression between v6.4.13 and v6.4.14

### ISSUE THREAD

**Issue by maetshju** [praat/praat#2764]
Some code change between v6.4.13 and v6.4.14 broke something about the FormantPath object.

Here is a basic script to make a sound to look at:

```praat
Create SpeechSynthesizer: "English (Great Britain)", "Female1"
To Sound: "This is some text.", "no"
To FormantPath (burg): 0.005, 5, 5500, 0.025, 50, 0.05, 4
```

When the FormantPath object is viewed with the sound in v6.4.13, the formant tracking appears as expected:
<details>
<summary>v.6.4.13 tracking image</summary>
<img width="960" alt="praat_6_4_13_formantpath" src="https://github.com/user-attachments/assets/0975e407-133a-4e34-b282-497537d8c793">
</details>

In v6.4.14, however, the formant tracking looks obviously wrong, with tracks drawn in a way that do not correspond to the formants visible in the spectrogram:

<details>
<summary>v6.4.14 tracking image</summary>
<img width="960" alt="praat_6_4_14_formantpath" src="https://github.com/user-attachments/assets/c7872877-7965-4756-b564-6d161b98be81">
</details>

This bug occurs on Windows, Mac, and Linux versions of Praat, even in the most recent version to date, v6.4.21. Additionally, the numbers that come from `Formant listing` in the editor window seem to match the tracks drawn in the editor, so it does not seem like it is just a visualization issue.

**Comment by davidweenink** [comment]
I will try to solve this problem. Thanks for reporting.

**Comment by davidweenink** [comment]
The problem has been solved.  The next version of Praat will restore the correct behavior. Thank you for reporting.

**Comment by maetshju** [comment]
Thank you! I really like using this feature with my students, so I am glad that it will be restored in the next version.
