### ISSUE TITLE
Building AUR package fails because INFO_ONE is undefined

### ISSUE THREAD

**Issue by Anaphory** [praat/praat#295]
On Arch Linux, I would like to install `praat`. There is an aur PKGBUILD for doing this (actually three, https://aur.archlinux.org/packages/praat-pulse-git/ is the one that looks like I want it, but this issue applies to all three), but the compilation fails in [praat_DataModeler_init.cpp](https://github.com/praat/praat/blob/master/dwtools/praat_DataModeler_init.cpp#L224) – that file assumes the `INFO_ONE` macro is defined, but [`praat.h`](https://github.com/praat/praat/blob/master/sys/praat.h#L614) has no such `#define`.

**Comment by Anaphory** [comment]
From the syntax of the other calls and macros, it looks like what's missing is

    #define INFO_ONE(klas)  FIND_ONE (klas)
    #define INFO_ONE_END  END

in [praat.h](https://github.com/praat/praat/blob/master/sys/praat.h), and with those two lines added, it does compile and package, but I have *no idea* what I did there, so I will not submit this as a pull request, which would look like I knew what I was doing.

**Comment by davidweenink** [comment]
INFO_ONE has been included now.
