### ISSUE TITLE
Opening editor from batch

### ISSUE THREAD

**Issue by Laqshay** [praat/praat#338]
I am trying to break audios into smaller parts on a linux server. But it requires opening an editor, which can't be done on batch. So is there a way to extract and save a specific portion of sound without opening the editor window, or a way to 'open' editor window while using praat from command line (batch)?

**Comment by drammock** [comment]
@Laqshay questions about *using* praat should be sent to the [praat users group](https://uk.groups.yahoo.com/neo/groups/praat-users/info) mailing list.  Regarding your specific question, with a sound object selected there is the `Extract part` command: `Extract part: start_time, end_time, window_shape, relative_width, preserve_times`.  When using praat interactively, it appears in the object window under the "convert" menu, when a sound object is selected.
