### ISSUE TITLE
CommandLine only version for Android

### ISSUE THREAD

**Issue by demoush** [praat/praat#345]
Hello,

Is it possible to cross compile Praat for Android ?  I only need the command line version without any graphics and sound packages.  I only want to execute basic praat script without user interaction.  

Best regards,

Jimmy

**Comment by demoush** [comment]
I managed to compile a android version with no graphic. 

Jimmy

**Comment by karthikhegde52** [comment]
Hi,
@demoush , can you please share the steps you followed to cross compile Praat for android platform?

Thanks & Regards,
Karthik

**Comment by demoush** [comment]
Hi,

Here are the steps...  the steps have been created by one of my friend.  I'm really not a linux guy.  Unfortunately it ended up with a runtime error when  I ran the binary compiled.   If you have any success based on what we started, I will be more than happy you let met know.


[praat.zip](https://github.com/praat/praat/files/1791237/praat.zip)

**Comment by karthikhegde52** [comment]
Hi @demoush,

Thanks for the reply. I was able to build praat for android by making use of the 'Makefile' that you shared. I added "-pie" in the main Makefile, to get rid of the "error: only position independent executables (PIE) are supported". 
I also got some runtime errors with the praat code version 6.0.37. But when I commented the code giving errors, I was able to run Praat on android smoothly(No Graphic version). 

Thanks & Regards,
Karthik

**Comment by demoush** [comment]
Hi Karthik,

Could you tell me the code you have commented so far (files and line number) or maybe send me a git diff ;) ?  I'll make a try on my side ?

Thanks for your help,

Demoush

**Comment by karthikhegde52** [comment]
Hi Demoush,

Sorry for late reply. Attached the Praat code that I was able to build. You need to change the Makefile and Makefile.defs files.
[praat-6.0.37.zip](https://github.com/praat/praat/files/1810486/praat-6.0.37.zip)

Regards,
Karthik

**Comment by purelog1c** [comment]
Hi Karthik @karthikhegde52 ,
I also need nogui praat just for calculations. Anyhow I am struggling so hard to create shared library for my flutter project. Could you give me some instructions how I could create .so ? Later I will use this shared library in FFI in dart to send and receive information. Consider that I am really new at this and need really quite solid instructions to understand... :/
