### ISSUE TITLE
Chinese characters not displaying in text annotations

### ISSUE THREAD

**Issue by rlaboiss** [praat/praat#348]
This problem has been reported as a bug report on the Debian package for praat (https://bugs.debian.org/859343). I am forwarding it here, hoping that you know how to fix it.

Best,

Rafael Laboissière

**Comment by PaulBoersma** [comment]
we're converting graphical text from Cairo to Pango, so this will be fixed.

**Comment by rlaboiss** [comment]
Do you know when the fix will be released?

**Comment by PaulBoersma** [comment]
the fix is available in the current source code on GitHub, and will be released with version 6.0.29, perhaps today.

**Comment by rlaboiss** [comment]
Great, thanks, it works.
