### ISSUE TITLE
Praat doesn't have a menu bar on ubuntu 16.04

### ISSUE THREAD

**Issue by centaurp6** [praat/praat#352]
I've installed Praat on my ubuntu 16.04LTS using "sudo apt-get install praat".
After starting the programme two windows appear: "Pratt objects" and "Praat picture", but both of them don't have  menu bars.
![2017-05-15 12-31-59](https://cloud.githubusercontent.com/assets/28703559/26054312/bc7142bc-3974-11e7-8158-4ce8830e315c.png)

**Comment by rolandomunoz** [comment]
If the menu doesn't appear in the **title bar** of Praat, it could be in the **menu bar** of your OS. 
![screenshot from 2017-05-15 06-56-45](https://cloud.githubusercontent.com/assets/18198623/26056674/f63ccc52-393b-11e7-83bd-03d3b3bc152a.png)
If you want the menus in the title bar of Praat, you could: 
- Go to All Settings > Appearance
- In the Behavior, `Show the menus for a window`, then use the second option.

![screenshot from 2017-05-15 06-57-20](https://cloud.githubusercontent.com/assets/18198623/26057078/88e47a86-393d-11e7-9260-f2a3eeb2cebf.png)

Is this your problem?

**Comment by meyersbs** [comment]
I recall having a similar issue. I assume you've tried this, but try clicking where the buttons should be; your theme might have the text set to that grey color.

**Comment by centaurp6** [comment]
My God, shame on me. I'm new to using Ubuntu, I did not know that the menus are displayed in the system menu bar. Many thanks.
