### ISSUE TITLE
Why a new executable name for "barren" praat?

### ISSUE THREAD

**Issue by jjatria** [praat/praat#390]
a0b9da5 introduced a new default executable name for Praat when compiled as _barren_.

What is the rationale behind this? This change means that computers that currently use automated build systems using a barren praat (including the ones I maintain), will either have to be modified to change the name of the executable, or will have to use a version of scripts that is specifically written to use that executable.

As an aside, is there any reason why a change like this, which will most likely result in breakage, is introduced without any warning or notification whatsoever?

**Comment by PaulBoersma** [comment]
you can just rename the executable to anything you like
