### ISSUE TITLE
6.0.31 "Object[xx].nrow" requires xx to be  number or a string, not an object

### ISSUE THREAD

**Issue by rolandomunoz** [praat/praat#438]
Hello,

I have tested the object[].nrow as shown in the [manual](http://www.fon.hum.uva.nl/praat/manual/Formulas_7__Attributes_of_objects.html) for Table and Sound objects. But I get the following message: 

> The expression "object[xx].nrow" requires xx to be number or a string, not an object.

Here is the code I use:
  > object[1].nrow

The other way works well:
  > Object_1.nrow

I do not understand why this happens, I've tested in Ubuntu 16.04 (64 bits) and Windows 7 (32 bits). I use Praat 6.0.31.

Could it be a bug?

Thank you in advance

**Comment by PaulBoersma** [comment]
yes, this was certainly a bug. Repaired for version 6.0.33. Thanks.
