### ISSUE TITLE
Praat script giving different results when run through command prompt from different folder that praat

### ISSUE THREAD

**Issue by zhafeez** [praat/praat#469]
Hi
Using the interface it works fine, but when run through script from the different folder (Script and sound files were in different folders than the praat) the output was not what it should be.

Praat version: 6.0.25

[output.zip](https://github.com/praat/praat/files/1336876/output.zip)
[praat_script.zip](https://github.com/praat/praat/files/1336864/praat_script.zip)
[108.zip](https://github.com/praat/praat/files/1336854/108.zip)

**Comment by PaulBoersma** [comment]
This report is not in a form that we can process. Please provide the script in your question, explain what output it should produce, what you did exactly, and what output it produced instead. No zip files where none are needed.

**Comment by PaulBoersma** [comment]
The script runs fine. Perhaps you have multiple versions of 108.wav. Without explicit steps to replicate the error we cannot comment any further.
