### ISSUE TITLE
Console Praat crashes on save PNG instruction

### ISSUE THREAD

**Issue by fahadash** [praat/praat#47]
Console Praat (praatcon.exe) 5.4.21 (September 29 Release) is crashing on Windows 8, and Windows 7 (those are the only ones I have checked with)

A sample script that generates the waveform and saves that as a PNG file is attached.

Unable to attach script due to some issue with Github interface, I am copy-pasting it below

```
#praat test file , Please change the following two paths
outputFolder$ = "C:\Temp\del\praat"
audioFile$ = "C:\Temp\del\praat\test.mp3"

if audioFile$ <> ""
	Read from file... 'audioFile$'
	audioName$ = selected$ ("Sound")
endif

Line width... 1
Viewport... 0 4 0 1
Colour... magenta
Draw... 0 0 0 0 no curve
Draw inner box

select Sound 'audioName$'
To Intensity... 80 0
Down to IntensityTier

select Sound 'audioName$'
To Pitch (ac)... 0.0 80 15 no 0.03 0.3 0.2 0.9 0.14 300
Down to PitchTier

select Intensity 'audioName$'
Viewport... 0 4 0.6 1.6

Colour... lime
Line width... 2
Draw... 0 0 0 0 no
#Text right... yes Intensity (dBs)

# Draw pitch track
select Pitch 'audioName$'
Viewport... 0 4 0.6 1.6

# Draw in either greyscale or color

Colour... blue

Line width... 1
Draw... 0 0 80 300 yes
Marks bottom every... 1 5 yes yes no
Line width... 2
Draw... 0 0 80 300 no

Viewport... 0 4 0 1.6
Save as 300-dpi PNG file... 'outputFolder$'\waveform.png
```

**Comment by fahadash** [comment]
Attached is the screenshot, and here is the link to download everything that I am using
https://www.dropbox.com/s/ch8ape0vokumskp/praat.zip?dl=0
Fix the paths in the script and from the command line, just issue the following command

c:\Path\to\Praatcon.exe c:\path\to\waveform_script.praat

![crash1](https://cloud.githubusercontent.com/assets/3836080/10341252/fe444bf0-6ce1-11e5-8704-e7335e8b7eaa.png)

**Comment by PaulBoersma** [comment]
Yes, replicated. Will solve.

**Comment by PaulBoersma** [comment]
repaired for 5.4.22 (GDI+ had to be initialized)

**Comment by fahadash** [comment]
It is a good practice to refer to the Issue number in your commit message like so #47 along with the # symbol. That links your commit to the issue automatically.

Where can I get the new exe?

**Comment by PaulBoersma** [comment]
Thanks for the tip. Will publish 5.4.22 on Thursday.
