### ISSUE TITLE
Performance of Praat nuclei v2 script for speech rate

### ISSUE THREAD

**Issue by fievelk** [praat/praat#482]
Hi everyone.
I want to compute the speech rate of an audio file using PRAAT. I'm currently using the [nuclei script v2](https://sites.google.com/site/speechrate/Home/praat-script-syllable-nuclei-v2). However, the computation seems to be very slow.

I'm not an expert of PRAAT scripting, so I don't know exactly if something could be improved to increase the performance of the script.

This is a benchmark using the script on 3 different files with different length.

```
Calculating speech rate for test-large.wav (33 minutes)
speech_rate: 68.8
elapsed time: 35.351608753204346

Calculating speech rate for test-medium.wav (20 minutes)
speech_rate: 75.6
elapsed time: 19.08372402191162

Calculating speech rate for test-small.wav (4 minutes)
speech_rate: 47.6
elapsed time: 5.445473909378052
```

I think the computation is taking too long. What do you think?

Do you have any suggestions? How would you improve the script?

**Comment by rolandomunoz** [comment]
This space is for Praat development. You should post you question in the [Praat Users Group](https://uk.groups.yahoo.com/neo/groups/praat-users/info).

**Comment by PaulBoersma** [comment]
the speed here seems to be 60 times faster than real time. No bug involved.
