### ISSUE TITLE
Poor Graphical Performance in Openbox, with and without compositor

### ISSUE THREAD

**Issue by nukedone** [praat/praat#485]
This software is my living.
I am using it under linux. The problem with the two desktop environments is that something interface looks fuzzy, that is, the buttons of segment duration are not redrawn. I am talking about XFCE and LXDE. Is there any solution to make clean interfeace in these two DEs.
Thank you very much.

**Comment by PaulBoersma** [comment]
Can you explain about what buttons you are talking, and what they look like?

**Comment by nukedone** [comment]
Sorry. It is the section delimiters in the sound view window that hold durations. I figured out that hardware compositing is needed in order for artefacts not to show. I eventually abandoned my low-end netbook due to the problems, or just put it aside as I filed a bug report against the components that trouble my computer.

⁣Sent from Blue ​

**Comment by PaulBoersma** [comment]
This has probably been solved in 6.1.24.
