### ISSUE TITLE
Unit test test_gsl fails randomly

### ISSUE THREAD

**Issue by rlaboiss** [praat/praat#487]
One of the unit test in file `dwtest/test_gsl.praat` is failing randomly.  For instance, [the automated test 
of the Debian praat package,](https://ci.debian.net/data/autopkgtest/unstable/amd64/p/praat/20171007_155701/log.gz) yields the following:

```
===== test_gsl.praat
Error: Script assertion fails in line 64 (false):
   abs((.res-.r)/(.res+.r)) < .tol; 2.708455507320178e-07=incompleteGammaP (3, 0.011791548967797105) (2.708455508759755e-07)
Script “/tmp/autopkgtest-virt-lxc.shared.kob6gng_/downtmp/build.2Bt/praat-6.0.33/dwtest/test_gsl.praat” not completed.
Praat: script command <<test_gsl.praat>> not completed.
```

The culprit seems to the following code in file `dwtest/test_gsl.praat`:

```
        for .i to 100
                .x = randomUniform (0, emax)
                call func_2args incompleteGammaP 3 .x 1-(1+.x+0.5*.x^2)*exp(-.x) 2*tol4
        endfor
```

It seems that, for small values of `x`, the expression `1-(1+.x+0.5*.x^2)*exp(-.x)` provides values significantly different values from those of the Incomplete Gamma function in GSL.

My inclination is to increase the tolerance of the test, but I would like to hear from the Praat authors whether there would be a more principled way of fixing the problem.

**Comment by PaulBoersma** [comment]
This has been fixed.
