### ISSUE TITLE
Praat fails on 

### ISSUE THREAD

**Issue by rlaboiss** [praat/praat#500]
In Debian, the praat package is [built](https://buildd.debian.org/status/package.php?p=praat) on all official architectures. The build fails on [armel](https://buildd.debian.org/status/fetch.php?pkg=praat&arch=armel&ver=6.0.34-1&stamp=1508126397&raw=0), [armhf](https://buildd.debian.org/status/fetch.php?pkg=praat&arch=armhf&ver=6.0.34-1&stamp=1508117557&raw=0), [mips](https://buildd.debian.org/status/fetch.php?pkg=praat&arch=mips&ver=6.0.34-1&stamp=1508116750&raw=0), and [mipsel](https://buildd.debian.org/status/fetch.php?pkg=praat&arch=mipsel&ver=6.0.34-1&stamp=1508180932&raw=0), with the error message:

```
Fatal error: Praat will crash. Notify the author (paul.boersma@uva.nl) with the following information:
Assertion failed in file "praat.cpp" at line 1627:
   sizeof (real80) >= 12
```

Indeed, the size of "long double" on those architectures is [8 bytes](https://wiki.debian.org/ArchitectureSpecificsMemo) and not 12 bytes, as expected.  What should be done here? Prevent the build of praat on those architectures?

**Comment by PaulBoersma** [comment]
I think Praat will run totally fine if that check is removed. Thanks for notifying me of the diversity.

**Comment by rlaboiss** [comment]
I built Praat on a Debian mips system with the following line in praat.cpp commented out:

```
    // Melder_assert (sizeof (real80) >= 12);
```

It compiles fine but all unit tests crash with segmentation faults.

**Comment by PaulBoersma** [comment]
Can you mention one of the things that go wrong? Or do you mean that Praat doesn't start up at all?

**Comment by rlaboiss** [comment]
Praat crashes at start up.

**Comment by PaulBoersma** [comment]
don't think this occurs any longer
