### ISSUE TITLE
Unit test fisherQ fails on some Linux architectures

### ISSUE THREAD

**Issue by rlaboiss** [praat/praat#502]
The Debian autobuilder system detects failures when building the praat package on some architectures.  It happens for the unit test in the script num/fisherQ.praat, with the follwing error message on architectures [arm64](https://buildd.debian.org/status/fetch.php?pkg=praat&arch=arm64&ver=6.0.35-1&stamp=1508599152&raw=0), [i386](https://buildd.debian.org/status/fetch.php?pkg=praat&arch=i386&ver=6.0.35-1&stamp=1508595355&raw=0), [ppc64el](https://buildd.debian.org/status/fetch.php?pkg=praat&arch=ppc64el&ver=6.0.35-1&stamp=1508596356&raw=0), and [s390x](https://buildd.debian.org/status/fetch.php?pkg=praat&arch=s390x&ver=6.0.35-1&stamp=1508594835&raw=0):

```
Error: Script assertion fails in line 13 (false):
   fisherQ (randomUniform (3, 4), 1, 100000) <> undefined
Script “/<<PKGBUILDDIR>>/test/num/fisherQ.praat” not completed.
Praat: script command <<num/fisherQ.praat>> not completed.

fisherQ test: 5.932714539946133e-11 0.00000000005932714540
```

For now, I will prevent the fisherQ.praat script to run at build time, but it would be good to fix the problem in the future.

**Comment by PaulBoersma** [comment]
This has been fixed.
