### ISSUE TITLE
Praat 6.0.35 - Praat Manual - Vector and Matrices - some commands don't work

### ISSUE THREAD

**Issue by rolandomunoz** [praat/praat#509]
Praat version: 6.0.35, 64 bits
OS: Ubuntu 16.04

In the section of **Vector and Matrices** of the **Scripting tutorial**, I have found a couple of things that doesn't work on my machine. I will list them here:

### 1: Cannot use the commands listed in the examples

When I select a Pitch object, and use the commands `Get times of frames` and `Get values in frames`, they don't work. Instead, I get a message which tells me that those commands are not available for the current selection. 

In the same way, Praat doesn't seem to recognize the function `sequence_by_centre#`. I get a message that this is an unknown function. 

### 2: Typo in some examples?
In another example it says that we can use the following functions to create vectors.

`randomGauss# (10000, 0.0, 1.0)`
`randomUniform# (10000, 0.0, 1.0)`

However when I copy those commands, Praat tells me that the first argument must be a vector. So, instead, I use this code and it works:

`randomGauss# (zero#(10000), 0.0, 1.0)`
`randomUniform# (zero#(10000), 0.0, 1.0)`

**Comment by PaulBoersma** [comment]
These work now.
