### ISSUE TITLE
Praat for command mode

### ISSUE THREAD

**Issue by shrestha2lt8** [praat/praat#513]
I have been using an old version of Praatcon.exe for the command mode. I want to upgrade it to the latest version. I have noticed that there is no separate version for the command mode. but I am having some difficulty to open this from the c#.

I was using below code for older version.

   var info = new ProcessStartInfo(@"C:\Praat\Praat.exe", "C:\Praat\run.praat")
            {
                WorkingDirectory = @"C:\Praat\",
                UseShellExecute = false,
                RedirectStandardOutput = true,
                RedirectStandardError = true,
                RedirectStandardInput = true,
                CreateNoWindow = true,
            };
			
   Process.Start(info);

There is extra command --run in the new version of Praat to run in the command mode. but I could not figure this out.

Is the new version compatible with c#? Please provide me sample code for c# if you have any.

**Comment by PaulBoersma** [comment]
Yes, just use `--run`:

    ProcessStartInfo(@"C:\Praat\Praat.exe", "--run", "C:\Praat\run.praat")
