### ISSUE TITLE
Is it possible to auto-reload a script file ?

### ISSUE THREAD

**Issue by chuyuanli** [praat/praat#542]
Thank you for this excellent software !

I think the best way to edit praat script file at the moment is to edit it in another text editor like sublime, atom or emacs where syntax highlighting and snippets are supported. Other functions such as syntax checking can be implemented later depending on the community need. And for this process to be more fluid an automatic reload is quite useful.

Is it possible ?

**Comment by djvill** [comment]
This is what I do: I edit my Praat script in Notepad++, which has a [user-defined syntax highlighting file for Praat](http://sadowsky.cl/praat.html#syntax) and save it as normal. Then, I have a dummy one-line script that I can re-run anytime I edit and save the script in Notepad++:
`include path/name.praat`
This lets me edit the Praat script in a more user-friendly environment without having to close and reload the script window in Praat over and over.

**Comment by PaulBoersma** [comment]
Both of you missed the `Reopen from disk` command in the File menu.
