### ISSUE TITLE
Help Student PRaat

### ISSUE THREAD

**Issue by KpanS** [praat/praat#568]
Hi, I'm student and for my master thesis I recorded words in a .wave file but I have to do : 1) zero crossing before and after each word, 2) normalization RMS amplitude with Praat. How do this?

But, before do this steps, should I separate each word and create a file for each word or should I do this stages with my original file (which contains all words)? 

I really need help. Thanks.

**Comment by meyersbs** [comment]
@KpanS I don't think this is the best place to be asking those questions. There are help manuals in various languages on the [Praat Site](http://www.fon.hum.uva.nl/praat/manualsByOthers.html), as well as good tutorials in [Section 2](http://www.fon.hum.uva.nl/paul/praat.html). If you cannot find the information you need in those resources, try checking [StackOverflow](https://stackoverflow.com/questions/tagged/praat) for existing questions, or post your own there.

**Comment by KpanS** [comment]
@meyersbs Thank you ! I'll do this. I delete my post.
