### ISSUE TITLE
Matrix_extensions_enums.h: not exist

### ISSUE THREAD

**Issue by IhorBr** [praat/praat#580]
../dwtools/Matrix_extensions.h:28:10: fatal error: Matrix_extensions_enums.h: No such file or directory

**Comment by petronny** [comment]
Same problem here

**Comment by cranndarach** [comment]
Same for me, including when installing `praat-git` or `praat-pulse-git` using yaourt.

**Comment by PaulBoersma** [comment]
Solved some time ago.
