### ISSUE TITLE
Did Any one had luck running the c++ code on Windows

### ISSUE THREAD

**Issue by inaat** [praat/praat#585]
I am trying to compile the C++ code. i have followed the instructions of how to make on windows 
first i have copied and rename the file makefile.defs using the following command

cp makefiles/makefile.defs.mingw64 ./makefile.defs

when i try make it gives error. i am trying it from the last 72 hours. Could any one help me how he has executed the code under windows environment ?

thanks in Advance.

**Comment by PaulBoersma** [comment]
If you don't specify the precise error, we cannot help.
