### ISSUE TITLE
Add Record (fixed time) to scripting language

### ISSUE THREAD

**Issue by rj-fisch** [praat/praat#594]
This function (Sound_Record_fixedTime from Sound.h and Sound_audio.cpp) is not in the scripting language, but it could be added and would be very useful.

What file is the code for the scripting language in?

**Comment by PaulBoersma** [comment]
The command `Record Sound (fixed time)...` is available as a menu command in the New menu, and is therefore available in the scripting language. To see its parameters, you can make the menu command visible via `Preferences -> Buttons...`. Example:

    Record Sound (fixed time): "Microphone", 0.1, 0.5, 44100, 1.0

**Comment by rj-fisch** [comment]
Thank you so much!

**Comment by thealk** [comment]
It appears that `Record Sound (fixed time)` is not able to select USB inputs (such as USB preamplifiers) from topics such as [here (see response by JM)](https://groups.io/g/Praat-Users-List/topic/58562535#7095) and [here](https://groups.io/g/Praat-Users-List/topic/58563482#7580). My own testing seems to support this so far; is there anyway to overcome this to be able to automate audio recordings with a USB input?
