### ISSUE TITLE
TextGrid Editor: weird overprinting and line breaks in text intervals (OSX)

### ISSUE THREAD

**Issue by psibre** [praat/praat#6]
On OSX 10.9.5, I've noticed that the way the labels are displayed in intervals of a TextGrid Editor has weird overprinting and line breaks (depending on window size, zoom level, interval length, and label).

In v5.4.11 through v5.4.15, it looks like this:
![5 4 11](https://cloud.githubusercontent.com/assets/1278639/9288055/0215925a-432c-11e5-8b60-ec2fb3021124.jpg)

But in v5.4.10 and before it was fine:
![5 4 10](https://cloud.githubusercontent.com/assets/1278639/9288063/2aacd296-432c-11e5-83ea-e1ab8fe7066e.jpg)

**Comment by psibre** [comment]
Perhaps we should add "labels" to be able to tag issues by operating system...

**Comment by PaulBoersma** [comment]
Yes, this bug was reported earlier this week. A consequence of making text drawing twice as fast on the Mac. Shall repair it for v5.4.16.

**Comment by jjatria** [comment]
Nice.
If this is something that you've already figured out will be fixed in 5.4.16, then you could add it to a milestone, so that you can keep track of what needs to be fixed by when.
Maintaining milestones can get troublesome with many small issues like this one, but with more complex ones, or if the list gets larger, then it's a feature that might come in handy.

**Comment by PaulBoersma** [comment]
hi José,

thanks for the tip.

best wishes,
Paul

> Op 16 aug. 2015, om 01:51 heeft José Joaquín Atria <notifications@github.com> het volgende geschreven:
> 
> Nice.
> If this is something that you've already figured out will be fixed in 5.4.16, then you could add it to a milestone, so that you can keep track of what needs to be fixed by when.
> Maintaining milestones can get troublesome with many small issues like this one, but with more complex ones, or if the list gets larger, then it's a feature that might come in handy.
> 
> —
> Reply to this email directly or view it on GitHub.
> 

_____

Paul Boersma
University of Amsterdam
Linguistics
Spuistraat 210, room 303
1012VT Amsterdam, The Netherlands
http://www.fon.hum.uva.nl/paul/

**Comment by PaulBoersma** [comment]
Solved by measuring each character separately, at least in text rectangles.
