### ISSUE TITLE
Possibility to add some lines every 1k or 500 Hz to have a better idea of formants when visualizing spectrograms ?

### ISSUE THREAD

**Issue by xiaoouwang** [praat/praat#605]
![image](https://user-images.githubusercontent.com/16024291/41055448-a67d7c18-69c1-11e8-9c3e-657240ed0f35.png)

Something like this, I know many softwares have this kind of marks to help teaching phonetics and I wonder if it's possible to implement the same feature in Praat.

Best regards,
xo

**Comment by PaulBoersma** [comment]
This would clutter up the user interface. Instead we chose to have a single frequency cursor, i.e. you can click anywhere in the spectrogram and a horizontal line, with the exact frequency, will show up.
