### ISSUE TITLE
Use Praat on iOS and Android

### ISSUE THREAD

**Issue by jl-DaDar** [praat/praat#629]
How do I do that? 
Can someone please provide guidance? Thanks.

**Comment by PaulBoersma** [comment]
you cannot. Praat relies too much on menus, windows and files to be usable on those platforms.

**Comment by namanmaheshwari97** [comment]
@jl-DaDar You could use [Parselmouth](https://github.com/YannickJadoul/Parselmouth), which is basically Praat in Python.

You could then use Flask to create an API for all the information you need (pitch, intensity, etc.)

**Comment by sogaiu** [comment]
I had some success building and running praat on Android via [termux + vnc](https://wiki.termux.com/wiki/Graphical_Environment).  It's not the most convenient setup to use for sure, but perhaps better than nothing when there is no access to an appropriate pc.

I'll try to put together detailed instructions later, but roughly what was necessary for building was:

* install appropriate dependencies
* make a symlink so `soundcard.h` was appropriately visisble
* use a modified `makefile.defs` (included below)

```
# File: makefile.defs.linux.termux

# System: Android via termux

CC ?= gcc
CXX ?= g++
LINK ?= g++

PKG_CONFIG ?= "pkg-config"

COMMONFLAGS = -D_FILE_OFFSET_BITS=64 -DUNIX -Dlinux -DHAVE_PULSEAUDIO `$(PKG_CONFIG) --cflags gtk+-3.0` \
	-Wreturn-type -Wunused -Wunused-parameter -Wuninitialized -O1 -g1 -pthread

CFLAGS = -std=gnu99 $(COMMONFLAGS) -Werror=missing-prototypes -Werror=implicit

CXXFLAGS = -std=c++17 $(COMMONFLAGS) -Wshadow

EXECUTABLE = praat

LIBS = `$(PKG_CONFIG) --libs gtk+-3.0` -lm -lpulse -lpthread -L /usr/lib/x86_64-linux-gnu

AR = ar
RANLIB = ls
ICON =
MAIN_ICON =
```

**Comment by sogaiu** [comment]
The following gist contains detailed steps for setting things up on an Android [1] device to use praat: https://gist.github.com/sogaiu/89babbaa7b2a44db4ca549b5dca3b1a1

I've also made a PR to the termux-packages project to add praat as a package in the hopes that setup can be simplified: https://github.com/termux/termux-packages/pull/12447

---

[1] [Android 12 might be a bit troublesome to get working reliably](https://github.com/termux/termux-app/issues/2366#issuecomment-1237468220), but with a small amount of tweaking, 12L seems to be working fine.  IIUC, versions 11 and below (through 7 ATM) may work ok and 13 allegedly works via some tweaking too.

**Comment by sogaiu** [comment]
FYI, the PR to the termux-packages repository has been merged: https://github.com/termux/termux-packages/pull/12447

I've been using praat on Android on a tablet using this method for some days now.  As mentioned before, recording of audio doesn't work, but opening audio files and visualizing them seems to be working ok.

**Comment by jiacheng-thermetery** [comment]
I've done it, albeit somewhat of a limited port and adaptation. Both iOS and Android are working from my phone. I agree that there a lot of menus, and exposing all of the Praat functionalities cleanly on your phone is a challenge, but I think this is a good starting point. 

https://github.com/jiacheng-thermetery/ios.wrapper.for.praat.github.io

![image](https://github.com/user-attachments/assets/6cdacb2e-77c5-4f30-9bef-792044880d67)



![image](https://github.com/user-attachments/assets/d3cf2fb1-ee24-4e5d-b384-6247ecbf8420)
