### ISSUE TITLE
broken link in online docs

### ISSUE THREAD

**Issue by drammock** [praat/praat#63]
On [the filtering page](http://www.fon.hum.uva.nl/praat/manual/Filtering.html) there is a broken link to the page on [band filtering in the frequency domain](http://www.fon.hum.uva.nl/praat/manual/band_filtering_in_the_frequency_domain.html).

**Comment by PaulBoersma** [comment]
yes, that was a change in capitalization. Apparently, our publishing operating system (Mac) thought that the file name "band_filtering..." was the same as "Band_filtering..." and didn't replace it. I have now cleaned it up.

**Comment by drammock** [comment]
Thanks!
