### ISSUE TITLE
Incorrect font kerning in man pages

### ISSUE THREAD

**Issue by jjatria** [praat/praat#7]
I feel this has been a long lasting bug, but seeing that the display of man pages seems to have been improved recently, I figured it made sense to add this in.

At least in Linux (tested on other systems, but confirmed in Kubuntu 14.04 with Praat 5.4.15), switching in the manual from a standard font to an italic font causes the italic to be printed on top of the end of the string in a normal font. Sample image below:

![manual](https://cloud.githubusercontent.com/assets/2975989/9291358/8c421c48-43b1-11e5-9652-c62d0655b040.png)

At its most serious, this can make some change-heavy passages impossible to understand, meaning users need to refer to the HTML documentation.

**Comment by PaulBoersma** [comment]
This page looks totally correct with Praat 5.4.16 on my Ubuntu 14.04 (64-bit). Did you use the binary distribution, or did you compile it yourself, and if the latter, what were the options and libraries?

> the display of man pages seems to have been improved recently

I know of no recent changes.

**Comment by PaulBoersma** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/3752591/9307118/bd25af04-44fc-11e5-97a4-5be3fca06947.png)

**Comment by jjatria** [comment]
Odd. To my memory, I don't think I've _ever_ used a Linux version of Praat in which this problem did not exist.

This problem normally has appeared to me together with another in which the text goes under the area for the scroll bar (meaning that the last bit of each line is hidden by the scroll bar). But when I checked just now, this did not happen. This is the "improvement" I thought had been added. But if nothing has changed there, then this is probably due to something else.

FWIW, in 5.4.16 in 32-bit Linux both problems are still there. I'll see if I can find a Linux version in which does _not_ happen and see what the difference is.

**Comment by PaulBoersma** [comment]
So ehh... your own compilation, or the latest binary from the Praat website?

**Comment by jjatria** [comment]
Oh, right: the binary available from the website.

But when I've compiled it myself I have still found the same problem. I'll compile the latest version and report back when it's complete.

**Comment by jjatria** [comment]
As I thought, the problem persists with a self-compiled version of Praat 5.4.16 for Linux (32 bit) running on Kubuntu 14.04.

![manual](https://cloud.githubusercontent.com/assets/2975989/9385663/75f96670-474f-11e5-87f9-1480cd174887.png)

Note also how the end of the line of text is hidden under the scroll bar. Am I the only one seeing this?

**Comment by jjatria** [comment]
I just tried a version compiled after #19, and this problem seems to be solved. Nice!

![manual](https://cloud.githubusercontent.com/assets/2975989/9551019/913f0978-4da6-11e5-8437-c61218eb1974.png)

**Comment by PaulBoersma** [comment]
This was due to a difference in character width between Times and Times New Roman, which I think is unusual (but perhaps one of them had integer numbers of pixels, the other fractional).
