### ISSUE TITLE
Bug - Save audio with Preserve time (Praat 6.0.42)

### ISSUE THREAD

**Issue by rolandomunoz** [praat/praat#744]
When I use `Save as WAV file...` or `Save as AIFF file...` for an extracted Sound object with the `Preserve times` option activated, the start time does not conserve if I open that new file.

**Comment by no-buddy** [comment]
This is not a bug. Non of those formats have that metadata.

**Comment by rolandomunoz** [comment]
You are right! I will close this issue. Thank you.
