### ISSUE TITLE
Editor script uses wrong sound

### ISSUE THREAD

**Issue by ph9001** [praat/praat#790]
When a TextGrid is opened with more than one sound in different editor windows, the wrong sound can be used by an editor script.

To reproduce, first run this setup script:

```
sound1 = Create Sound as pure tone: "tone", 1, 0, 0.4, 44100, 440, 0.2, 0.01, 0.01
textgrid = To TextGrid: "Mary John bell", "bell"
selectObject: sound1
sound2 = Copy: "silence"
Set part to zero: 0, 0, "at nearest zero crossing"
selectObject: sound1
plusObject: textgrid
View & Edit
selectObject: sound2
plusObject: textgrid
View & Edit
```

Then, in the editor opened with the silence, run this editor script:

```
Select: 0, 0.4
Extract selected sound (time from 0)
```

The resulting object contains the tone, not the expected silence.  Manually selecting `File > Extract selected sound (time from 0)` produces the correct result.  The same problem appears to be true for other editor menu commands that work with the sound.

Tested on Windows 10 with version 6.0.43.

**Comment by PaulBoersma** [comment]
> in the editor opened with the silence, run this editor script

This is not what happens. The editor script is independent of the TextGrid window; it's not "in" the editor. The only thing that relates the two windows to each other visually (in the title of the script window) is the ID and name of the object being edited, which is the same TextGrid in both cases. The WYSIWYG principle then dictates that the script should work on an open TextGrid window, but there are two of them, so the command is ambiguous. Praat 6.1.09 will issue a warning when this happens. We are open to suggestions about a WYSIWYG-supportable disambiguation strategy.
