### ISSUE TITLE
Button text cut off on Linux Gnome 3

### ISSUE THREAD

**Issue by Whisprin** [praat/praat#791]
Hello,
I'm running Arch Linux with Gnome 3.30.2 and Praat version 6.0.43.

The buttons in Praat are too small for the text, so that the button text gets cut off and is hard to read.
I took a [screenshot with the default theme Adwaita](https://user-images.githubusercontent.com/3153136/48066028-b5888080-e1cc-11e8-9c3b-0a5b21485eab.png) and another [screenshot with material-light-compact application theme](https://user-images.githubusercontent.com/3153136/48065728-ca184900-e1cb-11e8-852a-40ae41e11cba.png) of the main program window. Other windows of Praat are affected as well. I haven't seen this in any other application.

The precompiled Linux x64 binaries and the application which I compiled myself are both showing the same problem.
Does anyone have the same issue or a solution?

**Comment by jouml** [comment]
Hi,
seems to be a common problem with GTK-based desktops (Gnome, XFCE...). I think I've read about several ways to fix this. Mine is:
`alias praat='env GTK2_RC_FILES=/usr/share/themes/Numix/gtk-2.0/gtkrc /usr/local/bin/praat'`
i.e. run Praat with an appropriate GTK-2 theme, e.g. Numix. Hope that helps.

(Fedora/XFCE)

**Comment by Whisprin** [comment]
thanks @jouml

It does get a bit better, but it's still not good after setting the GTK2_RC_FILES environment variable.

Before:
![before](https://user-images.githubusercontent.com/3153136/49932254-daa59880-fec8-11e8-8bfe-eaab9b8f6076.png)

After:
![after](https://user-images.githubusercontent.com/3153136/49932253-daa59880-fec8-11e8-84c2-26061854c340.png)

**Comment by jouml** [comment]
Today I tested on a machine running Fedora/Gnome 3.30/Praat 6.0.43. Praat looked pretty good without specific theming; Gnome was set to the Arc theme (Gnome twaek tool).

**Comment by Artofaj** [comment]
So the only solution we have so far is indeed changing the global theme for working with Praat? :/
I've tried making a custom launcher with the variable `env GTK_THEME="some_theme:light" praat` but praat doesn't seem to honor the convention.

**Comment by PaulBoersma** [comment]
This should look better in the current version 6.1.05.

**Comment by vgel** [comment]
I was having this problem as well -- the solution for me was to switch to LoDPI mode instead of 2x scaled HiDPI mode. Pop OS makes this really easy (you can click the HiDPI notification to toggle), can't remember how to do this the regular Linux way though.
