### ISSUE TITLE
Unit test test_Discriminant.praat fails on i386 fior v6.0.46

### ISSUE THREAD

**Issue by rlaboiss** [praat/praat#852]
On an i386 Debian system:

    $ uname -a
    Linux barriere 4.9.0-8-amd64 #1 SMP Debian 4.9.130-2 (2018-10-27) i686 GNU/Linux

the unit test dwtest/test_Discriminant.praat fails for Praat version 6.0.46 (see at the end of this report the patch that I applied, in order to output the values of classify.fc[1] and classify.fc[2]):

    $ ./praat --version
    Praat 6.0.46 (January 3 2019)
    $ ./praat ./dwtest/test_Discriminant.praat
    test_Discriminant
    	Read Discriminant format 0 from disk
    	Query old and new Discriminant
    	Assert old and new Discriminant classify the same
    	classify.fc[1]: 0.08333333333333333
    	classify.fc[2]: 0.74
    Error: Script assertion fails in line 24 (false):
       classify.fc[1] = classify.fc[2]
    Script “/home/rafael/praat-6.0.46/./dwtest/test_Discriminant.praat” not completed.
    Praat: script command <<./dwtest/test_Discriminant.praat>> not completed.

It works perfectly with Praat version 4.0.43:

    $ praat --version
    Praat 6.0.43 (September 8 2018)
    $ praat ./dwtest/test_Discriminant.praat
    test_Discriminant
    	Read Discriminant format 0 from disk
    	Query old and new Discriminant
    	Assert old and new Discriminant classify the same
    	classify.fc[1]: 0.74
    	classify.fc[2]: 0.74
    test_Discriminant OK

This problem is not observed with version 6.0.46 on a amd64 architecture.

P.S.: Here is the patch:

    --- praat-6.0.46.orig/dwtest/test_Discriminant.praat
    +++ praat-6.0.46/dwtest/test_Discriminant.praat
    @@ -19,6 +19,8 @@ appendInfoLine: tab$ + "Query old and ne
     appendInfoLine: tab$ + "Assert old and new Discriminant classify the same"
     @classify: discriminant[1], tableOfReal, 1
     @classify: discriminant[2], tableOfReal, 2
    +appendInfoLine: tab$ + "classify.fc[1]: ", classify.fc[1]
    +appendInfoLine: tab$ + "classify.fc[2]: ", classify.fc[2]
     assert classify.fc[1] = classify.fc[2]
     
     procedure classify: .discriminant, .tableOfReal, .index

**Comment by PaulBoersma** [comment]
We are no longer testing Praat for i368 Linux, although the scripts runs correctly on i386 Windows and x64 Linux. Can you check whether the problem persists with version 6.0.49?

**Comment by rlaboiss** [comment]
Actually, ithe unit test works with version 6.0.48 of Praat on i386 Linux.  If no regression was introduced in version 6.0.49, it should also work that latter version.  I will test it in the near future.

**Comment by rlaboiss** [comment]
It works fine with version 6.0.49, also.  I am hereby closing this issue.
