### ISSUE TITLE
No help for Scale intensity...

### ISSUE THREAD

**Issue by jjatria** [praat/praat#86]
Selecting "Help" in the `Scale intensity...` command results in an error.

![error](https://cloud.githubusercontent.com/assets/2975989/10926387/ccc2a28a-828e-11e5-9948-e19f90d423c7.png)

Running Praat 6.0.04 on Kubuntu 14.04.

**Comment by PaulBoersma** [comment]
yes, three dots missing, now repaired.
Thanks
