### ISSUE TITLE
Cannot locate previously downloaded praat application

### ISSUE THREAD

**Issue by EdPedraza-Robles** [praat/praat#864]
Hello, I had previously downloaded praat successfully with the download manager and used the application with no problems. However, now I am unable to find the application from my MAC terminal or Finder. I then tried to re-download the application and found myself unable to download anything with the download manager again. Is there anywhere my praat application could have gone?

**Comment by PaulBoersma** [comment]
I don't think we supply Praat for download managers. Just download it from praat.org and move it to your Applications folder.
