### ISSUE TITLE
Audio playback problems in Linux

### ISSUE THREAD

**Issue by jjatria** [praat/praat#87]
With recent versions of Praat, I cannot play audio on Kubuntu 14.04 (32 bit). Reverting back to 5.4.22 I encounter no such problem. The problem exists in Praat 6.0 and above (6.0.04 included).

The error that pops up tells me to turn on PulseAudio in the Sound Playing Preferences window, but PulseAudio is already selected. Selecting "Alsa via PulseAudio" fixes the problem during the session, but that preference is reverted when restarting Praat, so it needs to be set again each time.

![error](https://cloud.githubusercontent.com/assets/2975989/10926677/6599862a-8291-11e5-94bf-3c7430813a25.png)

**Comment by drammock** [comment]
That screenshot says "portAudio" not "pulseAudio" (which are different devices). Which were you intending to use?

**Comment by jjatria** [comment]
Oh, you're right. I guess it's too late here. :)

> Which were you intending to use?

I'm not sure I understand this question, though. I wasn't intending to use a specific device. I mean, most of my system runs with PulseAudio, so I wasn't intending to change anything about that. But when using the recent versions of Praat this comes up every time I try to play a sound.

**Comment by drammock** [comment]
What I meant, @jjatria, is: please confirm which device you had selected. I for one would often get errors during sound playback on pre-6.0 versions of praat, e.g., when playing a sound in praat just after using the keyboard hotkeys to change system volume level.  I still get those errors with praat 6.0.04 if I ask praat to use `ALSA via PortAudio` (see screenshot, and note the different error message) but so far I never get errors when praat 6.0.04 output sound system is set to use `PulseAudio` (much gratitude to @PaulBoersma for this enhancement, by the way).

![screenshot from 2015-11-03 20 28 27](https://cloud.githubusercontent.com/assets/1810515/10929524/8c1dab1e-8269-11e5-86cd-aec204783d99.png)

Your error, in contrast, appears to be praat failing to connect to `PulseAudio`, and asking you to switch to `ALSA via PortAudio` as a fallback.  I have no speculations as to why this is happening; all I can say is that playing sounds works well for me via `PulseAudio` on both Ubuntu 14.04 (laptop) and Xubuntu 14.04 (desktop).  So unfortunately this is a "cannot reproduce" (albeit not on an identical system), and the best I can suggest is combing through the numerous Linux PulseAudio troubleshooting guides. Hopefully others have more encouraging things to say.

**Comment by PaulBoersma** [comment]
Could it be, José, that your Praat binary was created by yourself, with a makefile that doesn't link with libpulse and that doesn't set HAVE_PULSEAUDIO?

**Comment by jjatria** [comment]
> Could it be, José, that your Praat binary was created by yourself

No, all these were versions that I downloaded from the web. The first were downloaded from <praat.org>, but I tried the ones from Github as well, just in case. The error is still there.

> I for one would often get errors during sound playback on pre-6.0 versions of praat, e.g., when playing a sound in praat just after using the keyboard hotkeys to change system volume level

I've also had those errors for a long time, but for some reason the new PulseAudio support does not work for me. Not sure what step to take to troubleshoot this further.

> please confirm which device you had selected

What I tried to say in the first post was that `PulseAudio` is selected by default, and that doesn't work, but selecting `Alsa over PortAudio` works. The problem is that these settings get reset for me across sessions. Any idea why that might be?

**Comment by PaulBoersma** [comment]
Haha, I found it! It turns out that my hunch about the wrong makefile was very close. I suddenly remembered you telling me you used the 32-bit edition, and indeed all those positive reports we received about audio now suddenly working were from 64-bit Linuxes.

So it is us who used the wrong makefile for the 32-bit edition. When you build from sources with the right makefile.defs, you'll hear PulseAudio at work. Will publish 6.0.05 with the correct libs for 32-bit Linux, and that version will also fix the preference setting. Fortunately, Rafael used the correct makefile for his Debian package.

**Comment by jjatria** [comment]
Great! Look forward to the update.
