### ISSUE TITLE
weird overprinting (Linux)

### ISSUE THREAD

**Issue by agricolamz** [praat/praat#873]
For some reason selections are displayed incorrectly for main window and TextGrids. Here is an example:

![praat](https://user-images.githubusercontent.com/15956515/54025442-98c87d80-41ab-11e9-9b96-43a4eb185440.gif)

I have Praat 6.0.37 isntalled. Here is information about my [system](https://gist.github.com/agricolamz/9a8e41383fe0a2f9c0468e642ea575cc).

May be this issue duplicates #485...

**Comment by PaulBoersma** [comment]
This has probably been solved in 6.1.24.

**Comment by agricolamz** [comment]
It works! Thank you!
