### ISSUE TITLE
Graphics can NOT be displayed in macOS Mojave 10.14

### ISSUE THREAD

**Issue by wuminaquarius** [praat/praat#960]
Praat version: 6.0.50 and Apple macOS:
When compiling source code in macOS Mojave 10.14.4 and Xcode 10.2, graphics can NOT be displayed correctly.
(When compiling source code in macOS High Sierra 10.13 and Xcode 10.1, graphics can be displayed correctly)

![graphics](https://user-images.githubusercontent.com/33130334/56247755-dc988780-6073-11e9-81ed-e2bdcc55a16f.png)

**Comment by PaulBoersma** [comment]
This is why the xcodeproj file says that it needs "macOS 10.13" as the Base SDK. Until we fully support Dark Mode, you will have to copy the 10.13 SDK into your Xcode app.
