### ISSUE TITLE
About the pitch

### ISSUE THREAD

**Issue by ucasiggcas** [praat/praat#981]
Dear,

Thanks for your great project, when I use the software I find it is very wonderful, it can get the low frequency pitch.
![image](https://user-images.githubusercontent.com/35590066/57444883-bf766380-7283-11e9-9a84-2a73ef55cd19.png)

But for a student,it's a little difficult to find the headers or cpp files in so many files,
and if there are some test files in cpp for the pitch,it would be great.

So could you help me a lot ?
Thanks for your advice or suggestion.

Lychee

**Comment by ucasiggcas** [comment]
![image](https://user-images.githubusercontent.com/35590066/57444995-f9e00080-7283-11e9-9b32-542dd04d350c.png)

**Comment by PaulBoersma** [comment]
sorry, I don't understand what you are asking.
