### ISSUE TITLE
how to read the wav or RIFF file ?

### ISSUE THREAD

**Issue by ucasiggcas** [praat/praat#982]
Dear,

I have a question that how to use **Sound** to read wav or RIFF file ?

How ?

Any introduction ?

I want to read the audio file.

Thanks

**Comment by dbqpdb** [comment]
"Open" > "Read from file..." > choose your file.

Dan

**Comment by ucasiggcas** [comment]
@dbqpdb 
No ,I say use the source code ,not the software

**Comment by PaulBoersma** [comment]
Sound.cpp, Sound_to_Pitch.cpp, and their dependencies. The organization sof the source code corresponds (almost) one-to-one with the organization of commands in the Objects window.
