### ISSUE TITLE
how to new a Sound ?

### ISSUE THREAD

**Issue by ucasiggcas** [praat/praat#983]
Dear,

With the headers and cpp files , I find it was difficult to new a Sound object,

It always ups that can't transpose from autoSound to Sound.

Could you help me to new a Sound ?

And my wav file is as follows

[gz019.zip](https://github.com/praat/praat/files/3169924/gz019.zip)

And if any one could get the pitch with PRAAT C++ file, will be grateful.

Thanks 

Lychee Tsu

**Comment by dbqpdb** [comment]
Hi Lychee,

Could you let us know what you're trying to accomplish? I see the sound that you are trying to process, but what do you want to know about the sound? You'd like the pitch? You can do:

"Open" > "Read from file..." (choose the file) > "View & Edit"

Then choose "Pitch" > "Show Pitch" and you'll see the plot for the pitch track over time.

If you need something else, please let us know. Happy pitch-tracking! :)

Dan
