### ISSUE TITLE
Setting breakpoints Xcode

### ISSUE THREAD

**Issue by polvanrijn** [praat/praat#984]
Dear Praat-developers,

I'm interested in how the pitch algorithm (ac) in Praat exactly works/is implemented. I downloaded the Xcode project and built it successfully. It would be great to stop at certain breakpoints during execution. I set breakpoints at many positions in the program, however the program never stopped here. How can I interrupt the program execution to view the variables?

Thanks in advance!

Cheers,
Pol van Rijn

**Comment by luzpaz** [comment]
bump

**Comment by PaulBoersma** [comment]
This is a question about Xcode, not Praat. From the Xcode documentation:

```
Xcode won't pause at this breakpoint because it has not been resolved. Resolving it requires that:

The line at the breakpoint is compiled.
The compiler generates debug information that is not stripped out (check the Build Settings).
The library for the breakpoint is loaded.
```
